/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Jul 04 01:37:08 GMT 2026
 */

package org.jsoup.nodes;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class Attributes_ESTest_scaffolding {

  @org.junit.Rule
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.jsoup.nodes.Attributes"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "F:\\Ky_5\\SWT301_Materials\\RT-SWT-nhom2"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\qhung\\AppData\\Local\\Temp\\"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Attributes_ESTest_scaffolding.class.getClassLoader() ,
      "org.jsoup.helper.DataUtil",
      "org.jsoup.parser.TreeBuilder",
      "org.jsoup.nodes.Range",
      "org.jsoup.select.Evaluator$IndexEvaluator",
      "org.jsoup.select.Evaluator$IsOnlyOfType",
      "org.jsoup.select.Evaluator$TagStartsWith",
      "org.jsoup.select.Evaluator$IsEmpty",
      "org.jsoup.parser.Parser",
      "org.jsoup.select.Evaluator$ContainsWholeText",
      "org.jsoup.nodes.Entities$CoreCharset",
      "org.jsoup.internal.ControllableInputStream",
      "org.jsoup.select.Evaluator$AttributeWithValueMatching",
      "org.jsoup.internal.QuietAppendable$1",
      "org.jsoup.nodes.Range$Position",
      "org.jsoup.nodes.Element",
      "org.jsoup.select.Evaluator$IsNthChild",
      "org.jsoup.select.Evaluator$Class",
      "org.jsoup.select.Evaluator$MatchesOwn",
      "org.jsoup.select.StructuralEvaluator$Ancestor",
      "org.jsoup.select.Evaluator$AttributeKeyPair",
      "org.jsoup.select.Evaluator$ContainsWholeOwnText",
      "org.jsoup.select.Evaluator$IsNthLastOfType",
      "org.jsoup.internal.QuietAppendable$StringBuilderAppendable",
      "org.jsoup.select.CombiningEvaluator$And",
      "org.jsoup.select.Evaluator$IsLastOfType",
      "org.jsoup.select.Evaluator$Attribute",
      "org.jsoup.nodes.Document",
      "org.jsoup.nodes.Entities",
      "org.jsoup.select.Evaluator$AttributeWithValueContaining",
      "org.jsoup.parser.HtmlTreeBuilder",
      "org.jsoup.select.Evaluator$AllElements",
      "org.jsoup.select.StructuralEvaluator",
      "org.jsoup.select.Evaluator$AttributeWithValue",
      "org.jsoup.select.Evaluator$AttributeWithValueNot",
      "org.jsoup.nodes.Range$Spans",
      "org.jsoup.internal.QuietAppendable$BaseAppendable",
      "org.jsoup.select.NodeEvaluator$InstanceType",
      "org.jsoup.select.NodeEvaluator$MatchesValue",
      "org.jsoup.SerializationException",
      "org.jsoup.select.CombiningEvaluator$Or",
      "org.jsoup.nodes.EntitiesData",
      "org.jsoup.select.Evaluator$ContainsText",
      "org.jsoup.select.Evaluator$Id",
      "org.jsoup.select.Evaluator$IsNthOfType",
      "org.jsoup.select.StructuralEvaluator$PreviousSibling",
      "org.jsoup.select.Evaluator$IndexEquals",
      "org.jsoup.internal.QuietAppendable",
      "org.jsoup.select.NodeEvaluator$BlankValue",
      "org.jsoup.select.Selector$SelectorParseException",
      "org.jsoup.helper.ValidationException",
      "org.jsoup.nodes.Attributes$Dataset$DatasetIterator",
      "org.jsoup.select.StructuralEvaluator$Not",
      "org.jsoup.nodes.NodeInternals",
      "org.jsoup.parser.CharacterReader",
      "org.jsoup.select.Evaluator$IsFirstChild",
      "org.jsoup.select.Evaluator$Tag",
      "org.jsoup.nodes.Document$OutputSettings$Syntax",
      "org.jsoup.select.StructuralEvaluator$Root",
      "org.jsoup.internal.StringUtil",
      "org.jsoup.select.NodeEvaluator",
      "org.jsoup.nodes.Attributes$1",
      "org.jsoup.select.Evaluator$AttributeWithValueStarting",
      "org.jsoup.internal.QuietAppendable$BaseAppendable$Action",
      "org.jsoup.select.Evaluator$IndexGreaterThan",
      "org.jsoup.select.QueryParser",
      "org.jsoup.internal.SimpleStreamReader",
      "org.jsoup.select.Evaluator$MatchesWholeText",
      "org.jsoup.select.Evaluator$Matches",
      "org.jsoup.select.Selector",
      "org.jsoup.select.Evaluator$AttributeWithValueEnding",
      "org.jsoup.select.StructuralEvaluator$ImmediatePreviousSibling",
      "org.jsoup.select.Evaluator$IsOnlyChild",
      "org.jsoup.select.NodeEvaluator$ContainsValue",
      "org.jsoup.nodes.Entities$1",
      "org.jsoup.parser.TokenQueue",
      "org.jsoup.parser.ParseSettings",
      "org.jsoup.select.Evaluator$MatchesWholeOwnText",
      "org.jsoup.nodes.Node",
      "org.jsoup.select.Evaluator$AttributeStarting",
      "org.jsoup.select.Evaluator$ContainsOwnText",
      "org.jsoup.nodes.Attributes",
      "org.jsoup.select.Evaluator$IndexLessThan",
      "org.jsoup.nodes.Entities$EscapeMode",
      "org.jsoup.parser.XmlTreeBuilder",
      "org.jsoup.select.Evaluator$MatchText",
      "org.jsoup.nodes.Document$OutputSettings",
      "org.jsoup.select.CombiningEvaluator",
      "org.jsoup.select.Evaluator",
      "org.jsoup.internal.SoftPool",
      "org.jsoup.select.Evaluator$ContainsData",
      "org.jsoup.select.Evaluator$IsRoot",
      "org.jsoup.internal.Normalizer",
      "org.jsoup.nodes.Attributes$Dataset$EntrySet",
      "org.jsoup.nodes.Attributes$Dataset",
      "org.jsoup.helper.Validate",
      "org.jsoup.select.StructuralEvaluator$ImmediateParentRun",
      "org.jsoup.select.Evaluator$IsLastChild",
      "org.jsoup.select.Evaluator$IsNthLastChild",
      "org.jsoup.nodes.Attribute",
      "org.jsoup.nodes.Range$AttributeRange",
      "org.jsoup.internal.LineMap",
      "org.jsoup.select.Evaluator$CssNthEvaluator",
      "org.jsoup.select.Evaluator$IsFirstOfType"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.util.function.Consumer", false, Attributes_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Attributes_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.jsoup.nodes.Attributes",
      "org.jsoup.nodes.Attributes$1",
      "org.jsoup.nodes.Attributes$Dataset",
      "org.jsoup.internal.LineMap",
      "org.jsoup.nodes.Range$Position",
      "org.jsoup.nodes.Range",
      "org.jsoup.nodes.Range$AttributeRange",
      "org.jsoup.internal.SoftPool",
      "org.jsoup.internal.StringUtil",
      "org.jsoup.nodes.Document$OutputSettings$Syntax",
      "org.jsoup.nodes.Attribute",
      "org.jsoup.nodes.Entities$CoreCharset",
      "org.jsoup.nodes.Entities",
      "org.jsoup.nodes.EntitiesData",
      "org.jsoup.parser.CharacterReader",
      "org.jsoup.helper.Validate",
      "org.jsoup.nodes.Entities$EscapeMode",
      "org.jsoup.nodes.Entities$1",
      "org.jsoup.internal.QuietAppendable",
      "org.jsoup.internal.QuietAppendable$BaseAppendable",
      "org.jsoup.nodes.Document$OutputSettings",
      "org.jsoup.select.Selector",
      "org.jsoup.select.QueryParser",
      "org.jsoup.parser.TokenQueue",
      "org.jsoup.internal.Normalizer",
      "org.jsoup.select.Evaluator",
      "org.jsoup.select.Evaluator$Tag",
      "org.jsoup.select.Evaluator$AttributeKeyPair",
      "org.jsoup.select.Evaluator$AttributeWithValue",
      "org.jsoup.select.CombiningEvaluator",
      "org.jsoup.select.CombiningEvaluator$And",
      "org.jsoup.select.Evaluator$Attribute",
      "org.jsoup.select.CombiningEvaluator$Or",
      "org.jsoup.helper.DataUtil",
      "org.jsoup.parser.Parser",
      "org.jsoup.helper.ValidationException",
      "org.jsoup.internal.QuietAppendable$StringBuilderAppendable",
      "org.jsoup.nodes.Attributes$Dataset$EntrySet",
      "org.jsoup.nodes.Attributes$Dataset$DatasetIterator",
      "org.jsoup.nodes.Range$Spans",
      "org.jsoup.parser.ParseSettings",
      "org.jsoup.nodes.NodeInternals",
      "org.jsoup.parser.TreeBuilder",
      "org.jsoup.parser.HtmlTreeBuilder",
      "org.jsoup.parser.Token",
      "org.jsoup.parser.Token$Tag",
      "org.jsoup.parser.Token$EndTag",
      "org.jsoup.parser.Token$TokenType",
      "org.jsoup.parser.TokenData",
      "org.jsoup.parser.ParseErrorList",
      "org.jsoup.nodes.Node",
      "org.jsoup.nodes.Element$NodeList",
      "org.jsoup.nodes.Element",
      "org.jsoup.nodes.Document",
      "org.jsoup.parser.Tag",
      "org.jsoup.parser.HtmlTagOptions",
      "org.jsoup.nodes.Document$QuirksMode",
      "org.jsoup.parser.Tokeniser",
      "org.jsoup.parser.TokeniserState",
      "org.jsoup.parser.Token$Character",
      "org.jsoup.parser.Token$Doctype",
      "org.jsoup.parser.Token$Comment",
      "org.jsoup.parser.Token$StartTag",
      "org.jsoup.parser.Token$XmlDecl",
      "org.jsoup.internal.SharedConstants",
      "org.jsoup.parser.TagSet",
      "org.jsoup.parser.HtmlTreeBuilderState$7",
      "org.jsoup.parser.HtmlTreeBuilderState",
      "org.jsoup.SerializationException"
    );
  }
}
