/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 04 05:45:58 GMT 2026
 */

package org.apache.commons.csv;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.nio.charset.Charset;
import org.apache.commons.csv.ExtendedBufferedReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ExtendedBufferedReader_ESTest extends ExtendedBufferedReader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      StringReader stringReader0 = new StringReader("\rV");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      String string0 = extendedBufferedReader0.readLine();
      assertEquals("", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      StringReader stringReader0 = new StringReader("Wp\n");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      ExtendedBufferedReader extendedBufferedReader1 = new ExtendedBufferedReader(extendedBufferedReader0);
      String string0 = extendedBufferedReader1.readLine();
      assertEquals("Wp", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      Charset charset0 = Charset.defaultCharset();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0, charset0, true);
      // Undeclared exception!
      try { 
        extendedBufferedReader0.read((char[]) null, 8192, (-1924));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // char array
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      extendedBufferedReader0.mark(1379);
      extendedBufferedReader0.reset();
      assertFalse(extendedBufferedReader0.isClosed());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader((Reader) null, (Charset) null, true);
      char[] charArray0 = new char[7];
      int int0 = extendedBufferedReader0.read(charArray0, (-40), 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      char[] charArray0 = new char[3];
      int int0 = extendedBufferedReader0.read(charArray0, 1, 1);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StringReader stringReader0 = new StringReader("org.apache.commons.csv.ExtendedBufferedReader");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      ExtendedBufferedReader extendedBufferedReader1 = new ExtendedBufferedReader(extendedBufferedReader0);
      char[] charArray0 = new char[8];
      int int0 = extendedBufferedReader1.peek(charArray0);
      assertEquals(8, int0);
      
      long long0 = extendedBufferedReader0.getPosition();
      assertEquals(45L, long0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      Charset charset0 = Charset.defaultCharset();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0, charset0, true);
      ExtendedBufferedReader extendedBufferedReader1 = new ExtendedBufferedReader(extendedBufferedReader0);
      extendedBufferedReader1.readLine();
      long long0 = extendedBufferedReader0.getPosition();
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      StringReader stringReader0 = new StringReader("org.apache.commons.csv.ExtendedBufferedReader");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      extendedBufferedReader0.read();
      int int0 = extendedBufferedReader0.getLastChar();
      assertEquals(111, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      try { 
        extendedBufferedReader0.reset();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // mark == -1
         //
         verifyException("org.apache.commons.io.input.UnsynchronizedBufferedReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader((Reader) null);
      // Undeclared exception!
      try { 
        extendedBufferedReader0.readLine();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      extendedBufferedReader0.close();
      try { 
        extendedBufferedReader0.readLine();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Closed
         //
         verifyException("org.apache.commons.io.input.Input", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      char[] charArray0 = new char[0];
      // Undeclared exception!
      try { 
        extendedBufferedReader0.read(charArray0, 5, 5);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Range [5, 5 + 5) out of bounds for length 0
         //
         verifyException("org.apache.commons.io.IOUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      extendedBufferedReader0.close();
      try { 
        extendedBufferedReader0.read((char[]) null, 2021, 2021);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Closed
         //
         verifyException("org.apache.commons.io.input.Input", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader((Reader) null);
      // Undeclared exception!
      try { 
        extendedBufferedReader0.read();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      extendedBufferedReader0.close();
      try { 
        extendedBufferedReader0.read();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Closed
         //
         verifyException("org.apache.commons.io.input.Input", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      // Undeclared exception!
      try { 
        extendedBufferedReader0.mark((-2453));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.io.input.UnsynchronizedBufferedReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      extendedBufferedReader0.close();
      try { 
        extendedBufferedReader0.mark(13);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Closed
         //
         verifyException("org.apache.commons.io.input.Input", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      StringReader stringReader0 = new StringReader("\n");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      char[] charArray0 = new char[6];
      int int0 = extendedBufferedReader0.read(charArray0, 3, 3);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      Charset charset0 = Charset.defaultCharset();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0, charset0, true);
      char[] charArray0 = new char[7];
      int int0 = extendedBufferedReader0.peek(charArray0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      StringReader stringReader0 = new StringReader("org.apache.commons.csv.ExtendedBufferedReader");
      Charset charset0 = Charset.defaultCharset();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0, charset0, true);
      int int0 = extendedBufferedReader0.read();
      assertEquals(111, int0);
      
      long long0 = extendedBufferedReader0.getBytesRead();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      Charset charset0 = Charset.defaultCharset();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0, charset0, true);
      int int0 = extendedBufferedReader0.read();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      StringReader stringReader0 = new StringReader("\r");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      extendedBufferedReader0.read();
      int int0 = extendedBufferedReader0.read();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      StringReader stringReader0 = new StringReader("\n");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      int int0 = extendedBufferedReader0.read();
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      StringReader stringReader0 = new StringReader("\r\n");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      extendedBufferedReader0.read();
      int int0 = extendedBufferedReader0.read();
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      StringReader stringReader0 = new StringReader("dzqH jpb'");
      Charset charset0 = Charset.defaultCharset();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0, charset0, true);
      ExtendedBufferedReader extendedBufferedReader1 = new ExtendedBufferedReader(extendedBufferedReader0);
      String string0 = extendedBufferedReader1.readLine();
      assertEquals("dzqH jpb'", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      extendedBufferedReader0.read();
      int int0 = extendedBufferedReader0.read();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      StringReader stringReader0 = new StringReader("\r\n");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      String string0 = extendedBufferedReader0.readLine();
      assertEquals("", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      StringReader stringReader0 = new StringReader("org.apache.commons.csv.ExtendedBufferedReader");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      int int0 = extendedBufferedReader0.read();
      assertEquals(111, int0);
      
      long long0 = extendedBufferedReader0.getLineNumber();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      StringReader stringReader0 = new StringReader("\r\n");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      char[] charArray0 = new char[3];
      int int0 = extendedBufferedReader0.read(charArray0);
      assertEquals(2, int0);
      
      extendedBufferedReader0.read();
      long long0 = extendedBufferedReader0.getLineNumber();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      StringReader stringReader0 = new StringReader("\r\n");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      char[] charArray0 = new char[3];
      int int0 = extendedBufferedReader0.read(charArray0);
      assertEquals(2, int0);
      
      long long0 = extendedBufferedReader0.getLineNumber();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      StringReader stringReader0 = new StringReader("\r\n");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      long long0 = extendedBufferedReader0.getLineNumber();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      StringReader stringReader0 = new StringReader("\r");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      String string0 = extendedBufferedReader0.readLine();
      assertEquals("", string0);
      
      long long0 = extendedBufferedReader0.getLineNumber();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      StringReader stringReader0 = new StringReader("?");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      Charset charset0 = Charset.defaultCharset();
      ExtendedBufferedReader extendedBufferedReader1 = new ExtendedBufferedReader(extendedBufferedReader0, charset0, true);
      char[] charArray0 = new char[6];
      int int0 = extendedBufferedReader1.peek(charArray0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      Charset charset0 = Charset.defaultCharset();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0, charset0, false);
      assertTrue(extendedBufferedReader0.markSupported());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0);
      long long0 = extendedBufferedReader0.getBytesRead();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Reader reader0 = Reader.nullReader();
      Charset charset0 = Charset.defaultCharset();
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(reader0, charset0, true);
      long long0 = extendedBufferedReader0.getPosition();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      StringReader stringReader0 = new StringReader("dzqHGjpb'");
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader(stringReader0);
      int int0 = extendedBufferedReader0.getLastChar();
      assertEquals((-2), int0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      ExtendedBufferedReader extendedBufferedReader0 = new ExtendedBufferedReader((Reader) null);
      // Undeclared exception!
      try { 
        extendedBufferedReader0.close();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.io.input.UnsynchronizedBufferedReader", e);
      }
  }
}
