/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 04 02:01:02 GMT 2026
 */

package org.jsoup.examples;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import java.net.MalformedURLException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.examples.HtmlToPlainText;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;
import org.jsoup.parser.Parser;
import org.jsoup.parser.Tag;
import org.jsoup.select.Elements;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HtmlToPlainText_ESTest extends HtmlToPlainText_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("VZ[':g$mWOe@6^Y3", "VZ[':g$mWOe@6^Y3");
      document0.text("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36");
      String string0 = HtmlToPlainText.getPlainText(document0);
      assertEquals("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like \nGecko) Chrome/137.0.0.0 Safari/537.36", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // usage: java -jar jsoup-examples.jar url [selector]
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("hm", "hm");
      Element element0 = document0.prependElement("hm", "hm");
      element0.before((Node) document0);
      Elements elements0 = element0.nextElementSiblings();
      // Undeclared exception!
      HtmlToPlainText.trimParents(elements0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      // Undeclared exception!
      try { 
        HtmlToPlainText.trimParents((Elements) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "http://www.w3.org/2000/svg";
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // HTTP error fetching URL. Status=404, URL=[http://www.w3.org/2000/svg]
         //
         verifyException("org.jsoup.helper.HttpConnection$Response", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "http://www.w3.org/1998/Math/MathML\norg.jsoup.examples.HtmlToPlainText$FormattingVisitor";
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: MalformedURLException");
      
      } catch(MalformedURLException e) {
         //
         // Illegal character in path at index 34: http://www.w3.org/1998/Math/MathML
         // org.jsoup.examples.HtmlToPlainText$FormattingVisitor
         //
         verifyException("org.jsoup.helper.CookieUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      // Undeclared exception!
      try { 
        HtmlToPlainText.main((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.examples.HtmlToPlainText", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "li";
      // Undeclared exception!
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The supplied URL, 'li', is malformed. Make sure it is an absolute URL, and starts with 'http://' or 'https://'. See https://jsoup.org/cookbook/extracting-data/working-with-urls
         //
         verifyException("org.jsoup.helper.HttpConnection", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      // Undeclared exception!
      try { 
        HtmlToPlainText.getPlainText((Element) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Object must not be null
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Document document0 = Parser.parse(".", ".");
      document0.appendChild(document0);
      // Undeclared exception!
      HtmlToPlainText.getPlainText(document0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Tag tag0 = new Tag((String) null, "");
      Element element0 = new Element(tag0, "dt");
      // Undeclared exception!
      try { 
        HtmlToPlainText.getPlainText(element0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Document document0 = Parser.parse(".", ".");
      Elements elements0 = document0.getElementsByAttributeValueNot(".", ".");
      Elements elements1 = HtmlToPlainText.trimParents(elements0);
      assertEquals(1, elements1.size());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Document document0 = Parser.parse("org.jsoup.parser.Token$EOF", "org.jsoup.parser.Token$EOF");
      Elements elements0 = document0.children();
      Elements elements1 = HtmlToPlainText.trimParents(elements0);
      assertNotSame(elements1, elements0);
      assertTrue(elements1.equals((Object)elements0));
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Elements elements0 = new Elements();
      Elements elements1 = HtmlToPlainText.trimParents(elements0);
      assertNotSame(elements1, elements0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Document document0 = new Document("http://www.w3.org/1998/Math/MathML");
      document0.text(" ");
      document0.title("n4*E`/&|}rc ");
      String string0 = HtmlToPlainText.getPlainText(document0);
      assertEquals("n4*E`/&|}rc ", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("                 ", "org.jsoup.examples.HtmlToPlainText$FormattingVisitor");
      document0.title("org.jsoup.examples.HtmlToPlainText$FormattingVisitor");
      String string0 = HtmlToPlainText.getPlainText(document0);
      assertEquals("org.jsoup.examples.HtmlToPlainText$FormattingVisitor ", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment(" ", " ");
      HtmlToPlainText.getPlainText(document0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Element element0 = new Element("a");
      String string0 = HtmlToPlainText.getPlainText(element0);
      assertEquals(" <>", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Element element0 = new Element("h4");
      String string0 = HtmlToPlainText.getPlainText(element0);
      assertEquals("\n\n", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Element element0 = new Element("dt");
      String string0 = HtmlToPlainText.getPlainText(element0);
      assertEquals("  \n", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Element element0 = new Element("\nli", "\nli");
      String string0 = HtmlToPlainText.getPlainText(element0);
      assertEquals("\n * ", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      String[] stringArray0 = new String[2];
      // Undeclared exception!
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The 'url' parameter must not be empty.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String[] stringArray0 = new String[13];
      // Undeclared exception!
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // usage: java -jar jsoup-examples.jar url [selector]
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      HtmlToPlainText htmlToPlainText0 = new HtmlToPlainText();
  }
}
