/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 23 14:16:33 GMT 2026
 */

package org.apache.commons.collections4.iterators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.ListIterator;
import java.util.NoSuchElementException;
import org.apache.commons.collections4.Transformer;
import org.apache.commons.collections4.functors.CloneTransformer;
import org.apache.commons.collections4.functors.InstanceofPredicate;
import org.apache.commons.collections4.functors.TransformerClosure;
import org.apache.commons.collections4.iterators.ListIteratorWrapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ListIteratorWrapper_ESTest extends ListIteratorWrapper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Class<Object> class0 = Object.class;
      InstanceofPredicate instanceofPredicate0 = new InstanceofPredicate(class0);
      Iterator<InstanceofPredicate> iterator0 = (Iterator<InstanceofPredicate>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(instanceofPredicate0, (Object) null).when(iterator0).next();
      ListIteratorWrapper<InstanceofPredicate> listIteratorWrapper0 = new ListIteratorWrapper<InstanceofPredicate>(iterator0);
      listIteratorWrapper0.next();
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      listIteratorWrapper1.next();
      listIteratorWrapper1.remove();
      assertTrue(listIteratorWrapper0.hasPrevious());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Class<Object> class0 = Object.class;
      InstanceofPredicate instanceofPredicate0 = new InstanceofPredicate(class0);
      Iterator<InstanceofPredicate> iterator0 = (Iterator<InstanceofPredicate>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(instanceofPredicate0, (Object) null).when(iterator0).next();
      ListIteratorWrapper<InstanceofPredicate> listIteratorWrapper0 = new ListIteratorWrapper<InstanceofPredicate>(iterator0);
      listIteratorWrapper0.next();
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      listIteratorWrapper1.next();
      listIteratorWrapper1.previous();
      Object object0 = listIteratorWrapper1.next();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Iterator<InstanceofPredicate> iterator0 = (Iterator<InstanceofPredicate>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(iterator0).next();
      ListIteratorWrapper<InstanceofPredicate> listIteratorWrapper0 = new ListIteratorWrapper<InstanceofPredicate>(iterator0);
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      listIteratorWrapper1.next();
      int int0 = listIteratorWrapper0.previousIndex();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Class<Object> class0 = Object.class;
      InstanceofPredicate instanceofPredicate0 = new InstanceofPredicate(class0);
      Iterator<InstanceofPredicate> iterator0 = (Iterator<InstanceofPredicate>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(true, false).when(iterator0).hasNext();
      doReturn(instanceofPredicate0, (Object) null).when(iterator0).next();
      ListIteratorWrapper<InstanceofPredicate> listIteratorWrapper0 = new ListIteratorWrapper<InstanceofPredicate>(iterator0);
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      listIteratorWrapper1.next();
      Transformer<InstanceofPredicate, InstanceofPredicate> transformer0 = CloneTransformer.cloneTransformer();
      TransformerClosure<InstanceofPredicate> transformerClosure0 = new TransformerClosure<InstanceofPredicate>(transformer0);
      listIteratorWrapper0.forEachRemaining(transformerClosure0);
      int int0 = listIteratorWrapper0.previousIndex();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Iterator<InstanceofPredicate> iterator0 = (Iterator<InstanceofPredicate>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(iterator0).next();
      ListIteratorWrapper<InstanceofPredicate> listIteratorWrapper0 = new ListIteratorWrapper<InstanceofPredicate>(iterator0);
      listIteratorWrapper0.next();
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      int int0 = listIteratorWrapper1.nextIndex();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(listIterator0);
      // Undeclared exception!
      try { 
        listIteratorWrapper0.set(listIterator0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.LinkedList$ListItr", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator();
      linkedList0.add((Object) listIterator0);
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(listIterator0);
      // Undeclared exception!
      try { 
        listIteratorWrapper0.remove();
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.LinkedList$ListItr", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(listIterator0);
      linkedList0.offerLast(listIterator0);
      // Undeclared exception!
      try { 
        listIteratorWrapper0.previous();
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.LinkedList$ListItr", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Iterator<Object> iterator0 = linkedList0.descendingIterator();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(iterator0);
      try { 
        listIteratorWrapper0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.LinkedList$ListItr", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator();
      linkedList0.add((Object) listIterator0);
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(listIterator0);
      // Undeclared exception!
      try { 
        listIteratorWrapper0.next();
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.LinkedList$ListItr", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator();
      linkedList0.add((Object) listIterator0);
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(listIterator0);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        listIteratorWrapper0.add(object0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.LinkedList$ListItr", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ListIteratorWrapper<Object> listIteratorWrapper0 = null;
      try {
        listIteratorWrapper0 = new ListIteratorWrapper<Object>((Iterator<?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // iterator
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Iterator<Integer> iterator0 = linkedList0.descendingIterator();
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      try { 
        listIteratorWrapper0.set((Integer) null);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // ListIteratorWrapper does not support optional operations of ListIterator.
         //
         verifyException("org.apache.commons.collections4.iterators.ListIteratorWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Iterator<Integer> iterator0 = linkedList0.descendingIterator();
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      int int0 = listIteratorWrapper0.previousIndex();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Class<Object> class0 = Object.class;
      InstanceofPredicate instanceofPredicate0 = new InstanceofPredicate(class0);
      Iterator<InstanceofPredicate> iterator0 = (Iterator<InstanceofPredicate>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(instanceofPredicate0, (Object) null).when(iterator0).next();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(iterator0);
      listIteratorWrapper0.next();
      listIteratorWrapper0.next();
      listIteratorWrapper0.reset();
      listIteratorWrapper0.next();
      listIteratorWrapper0.previous();
      assertFalse(listIteratorWrapper0.hasPrevious());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Iterator<Integer> iterator0 = linkedList0.descendingIterator();
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      int int0 = listIteratorWrapper0.nextIndex();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Iterator<InstanceofPredicate> iterator0 = (Iterator<InstanceofPredicate>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn((InstanceofPredicate) null, (Object) null).when(iterator0).next();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(iterator0);
      listIteratorWrapper0.next();
      listIteratorWrapper0.next();
      listIteratorWrapper0.reset();
      try { 
        listIteratorWrapper0.remove();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot remove element at index 0.
         //
         verifyException("org.apache.commons.collections4.iterators.ListIteratorWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      linkedList0.addLast((Integer) null);
      Iterator<Integer> iterator0 = linkedList0.descendingIterator();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(iterator0);
      listIteratorWrapper0.next();
      listIteratorWrapper0.previous();
      listIteratorWrapper0.remove();
      assertFalse(listIteratorWrapper0.hasPrevious());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Iterator<InstanceofPredicate> iterator0 = (Iterator<InstanceofPredicate>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(iterator0);
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      try { 
        listIteratorWrapper1.remove();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot remove element at index -1.
         //
         verifyException("org.apache.commons.collections4.iterators.ListIteratorWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Iterator<Integer> iterator0 = linkedList0.descendingIterator();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(iterator0);
      try { 
        listIteratorWrapper0.remove();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Cannot remove element at index -1.
         //
         verifyException("org.apache.commons.collections4.iterators.ListIteratorWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(listIterator0);
      int int0 = listIteratorWrapper0.previousIndex();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Iterator<InstanceofPredicate> iterator0 = (Iterator<InstanceofPredicate>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn((InstanceofPredicate) null, (Object) null).when(iterator0).next();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(iterator0);
      listIteratorWrapper0.next();
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      listIteratorWrapper1.next();
      listIteratorWrapper1.reset();
      assertFalse(listIteratorWrapper1.hasPrevious());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Iterator<Integer> iterator0 = linkedList0.descendingIterator();
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      try { 
        listIteratorWrapper0.previous();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.iterators.ListIteratorWrapper", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Integer integer0 = new Integer(9956);
      linkedList0.add((Object) integer0);
      Iterator<Object> iterator0 = linkedList0.descendingIterator();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(iterator0);
      assertFalse(listIteratorWrapper0.hasPrevious());
      
      listIteratorWrapper0.next();
      boolean boolean0 = listIteratorWrapper0.hasPrevious();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Iterator<Integer> iterator0 = linkedList0.descendingIterator();
      ListIteratorWrapper<Integer> listIteratorWrapper0 = new ListIteratorWrapper<Integer>(iterator0);
      ListIteratorWrapper<Object> listIteratorWrapper1 = new ListIteratorWrapper<Object>(listIteratorWrapper0);
      boolean boolean0 = listIteratorWrapper1.hasPrevious();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Iterator<Object> iterator0 = linkedList0.descendingIterator();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(iterator0);
      boolean boolean0 = listIteratorWrapper0.hasPrevious();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      linkedList0.addLast((Integer) null);
      Iterator<Integer> iterator0 = linkedList0.descendingIterator();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(iterator0);
      listIteratorWrapper0.next();
      assertTrue(listIteratorWrapper0.hasPrevious());
      
      listIteratorWrapper0.previous();
      boolean boolean0 = listIteratorWrapper0.hasNext();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Iterator<InstanceofPredicate> iterator0 = (Iterator<InstanceofPredicate>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(iterator0).hasNext();
      ListIteratorWrapper<InstanceofPredicate> listIteratorWrapper0 = new ListIteratorWrapper<InstanceofPredicate>(iterator0);
      boolean boolean0 = listIteratorWrapper0.hasNext();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(listIterator0);
      Object object0 = new Object();
      listIteratorWrapper0.add(object0);
      assertTrue(listIteratorWrapper0.hasPrevious());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Iterator<Integer> iterator0 = linkedList0.descendingIterator();
      ListIteratorWrapper<Object> listIteratorWrapper0 = new ListIteratorWrapper<Object>(iterator0);
      try { 
        listIteratorWrapper0.add(linkedList0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // ListIteratorWrapper does not support optional operations of ListIterator.
         //
         verifyException("org.apache.commons.collections4.iterators.ListIteratorWrapper", e);
      }
  }
}
