# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import requests.adapters as module_0
import requests.models as module_1
import requests.exceptions as module_2
import urllib3.exceptions as module_3
import urllib3.util.url as module_4

def test_case_0():
    base_adapter_0 = module_0.BaseAdapter()
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0

def test_case_1():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0

def test_case_2():
    response_0 = module_1.Response()
    h_t_t_p_adapter_0 = module_0.HTTPAdapter(max_retries=response_0)
    assert f'{type(h_t_t_p_adapter_0).__module__}.{type(h_t_t_p_adapter_0).__qualname__}' == 'requests.adapters.HTTPAdapter'
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    with pytest.raises(module_2.InvalidURL):
        h_t_t_p_adapter_0.send(response_0)

@pytest.mark.xfail(strict=True)
def test_case_3():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    h_t_t_p_adapter_0.proxy_manager_for(h_t_t_p_adapter_0)

@pytest.mark.xfail(strict=True)
def test_case_4():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    str_0 = 'vsb5A\x0b_/M\r\x0b,>\t0'
    h_t_t_p_adapter_0.proxy_manager_for(str_0)

@pytest.mark.xfail(strict=True)
def test_case_5():
    module_0.SOCKSProxyManager()

@pytest.mark.xfail(strict=True)
def test_case_6():
    base_adapter_0 = module_0.BaseAdapter()
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    base_adapter_0.send(base_adapter_0, timeout=base_adapter_0, verify=base_adapter_0)

def test_case_7():
    response_0 = module_1.Response()
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    with pytest.raises(module_2.InvalidURL):
        h_t_t_p_adapter_0.send(response_0, response_0, response_0, response_0)

@pytest.mark.xfail(strict=True)
def test_case_8():
    base_adapter_0 = module_0.BaseAdapter()
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    base_adapter_0.close()

@pytest.mark.xfail(strict=True)
def test_case_9():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    h_t_t_p_adapter_0.build_response(h_t_t_p_adapter_0, h_t_t_p_adapter_0)

def test_case_10():
    base_adapter_0 = module_0.BaseAdapter()
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    h_t_t_p_adapter_0 = module_0.HTTPAdapter(pool_maxsize=base_adapter_0)
    assert f'{type(h_t_t_p_adapter_0).__module__}.{type(h_t_t_p_adapter_0).__qualname__}' == 'requests.adapters.HTTPAdapter'
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    h_t_t_p_adapter_0.add_headers(base_adapter_0)

@pytest.mark.xfail(strict=True)
def test_case_11():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    h_t_t_p_adapter_0.get_connection_with_tls_context(h_t_t_p_adapter_0, h_t_t_p_adapter_0, cert=h_t_t_p_adapter_0)

def test_case_12():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    h_t_t_p_adapter_0.close()

@pytest.mark.xfail(strict=True)
def test_case_13():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    h_t_t_p_adapter_0.request_url(h_t_t_p_adapter_0, h_t_t_p_adapter_0)

@pytest.mark.xfail(strict=True)
def test_case_14():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    h_t_t_p_adapter_0.send(h_t_t_p_adapter_0, cert=h_t_t_p_adapter_0)

@pytest.mark.xfail(strict=True)
def test_case_15():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    h_t_t_p_adapter_0.__getstate__()
    h_t_t_p_adapter_0.proxy_manager_for(h_t_t_p_adapter_0)

def test_case_16():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    none_type_0 = h_t_t_p_adapter_0.close()
    str_0 = '\t{r5$lRL%DrX9'
    str_1 = ',knKo"'
    dict_0 = {str_0: none_type_0, str_1: str_0, str_1: none_type_0, str_0: h_t_t_p_adapter_0}
    none_type_1 = h_t_t_p_adapter_0.__setstate__(dict_0)
    assert f'{type(h_t_t_p_adapter_0.	{r5$lRL%DrX9).__module__}.{type(h_t_t_p_adapter_0.	{r5$lRL%DrX9).__qualname__}' == 'requests.adapters.HTTPAdapter'
    assert h_t_t_p_adapter_0.,knKo" is None

def test_case_17():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    str_0 = '&hG'
    var_0 = h_t_t_p_adapter_0.get_connection(str_0)
    assert f'{type(var_0).__module__}.{type(var_0).__qualname__}' == 'urllib3.connectionpool.HTTPConnectionPool'
    assert var_0.host == '&hg'
    assert var_0.port == 80
    assert var_0.headers == {}
    assert f'{type(var_0.timeout).__module__}.{type(var_0.timeout).__qualname__}' == 'urllib3.util.timeout.Timeout'
    assert f'{type(var_0.retries).__module__}.{type(var_0.retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert f'{type(var_0.pool).__module__}.{type(var_0.pool).__qualname__}' == 'queue.LifoQueue'
    assert var_0.block is False
    assert var_0.proxy is None
    assert var_0.proxy_headers == {}
    assert var_0.proxy_config is None
    assert var_0.num_connections == 0
    assert var_0.num_requests == 0
    assert var_0.conn_kw == {'blocksize': 16384}

@pytest.mark.xfail(strict=True)
def test_case_18():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    str_0 = ''
    h_t_t_p_adapter_0.cert_verify(str_0, str_0, h_t_t_p_adapter_0, h_t_t_p_adapter_0)

def test_case_19():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    str_0 = ''
    var_0 = h_t_t_p_adapter_0.cert_verify(h_t_t_p_adapter_0, str_0, str_0, str_0)
    assert h_t_t_p_adapter_0.cert_reqs == 'CERT_NONE'
    assert h_t_t_p_adapter_0.ca_certs is None
    assert h_t_t_p_adapter_0.ca_cert_dir is None

@pytest.mark.xfail(strict=True)
def test_case_20():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    str_0 = 'L6;6]Q>'
    h_t_t_p_adapter_0.cert_verify(h_t_t_p_adapter_0, str_0, str_0, h_t_t_p_adapter_0)

def test_case_21():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    str_0 = ''
    var_0 = h_t_t_p_adapter_0.cert_verify(h_t_t_p_adapter_0, str_0, str_0, str_0)
    assert h_t_t_p_adapter_0.cert_reqs == 'CERT_NONE'
    assert h_t_t_p_adapter_0.ca_certs is None
    assert h_t_t_p_adapter_0.ca_cert_dir is None

def test_case_22():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    str_0 = 'hxA.v;'
    with pytest.raises(OSError):
        h_t_t_p_adapter_0.cert_verify(h_t_t_p_adapter_0, str_0, str_0, str_0)

@pytest.mark.xfail(strict=True)
def test_case_23():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    str_0 = '7}'
    h_t_t_p_adapter_0.cert_verify(h_t_t_p_adapter_0, str_0, str_0, h_t_t_p_adapter_0)

@pytest.mark.xfail(strict=True)
def test_case_24():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    none_type_0 = None
    read_timeout_error_0 = module_3.ReadTimeoutError(none_type_0, none_type_0, h_t_t_p_adapter_0)
    h_t_t_p_adapter_0.request_url(read_timeout_error_0, none_type_0)

def test_case_25():
    response_0 = module_1.Response()
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    with pytest.raises(module_2.InvalidURL):
        h_t_t_p_adapter_0.send(response_0, cert=h_t_t_p_adapter_0)

def test_case_26():
    response_0 = module_1.Response()
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    var_0 = h_t_t_p_adapter_0.build_response(response_0, response_0)
    assert f'{type(var_0).__module__}.{type(var_0).__qualname__}' == 'requests.models.Response'
    assert var_0.status_code is None
    assert f'{type(var_0.headers).__module__}.{type(var_0.headers).__qualname__}' == 'requests.structures.CaseInsensitiveDict'
    assert len(var_0.headers) == 0
    assert f'{type(var_0.raw).__module__}.{type(var_0.raw).__qualname__}' == 'requests.models.Response'
    assert var_0.url is None
    assert var_0.encoding is None
    assert var_0.history == []
    assert var_0.reason is None
    assert f'{type(var_0.cookies).__module__}.{type(var_0.cookies).__qualname__}' == 'requests.cookies.RequestsCookieJar'
    assert len(var_0.cookies) == 0
    assert f'{type(var_0.elapsed).__module__}.{type(var_0.elapsed).__qualname__}' == 'datetime.timedelta'
    assert f'{type(var_0.request).__module__}.{type(var_0.request).__qualname__}' == 'requests.models.Response'
    assert f'{type(var_0.connection).__module__}.{type(var_0.connection).__qualname__}' == 'requests.adapters.HTTPAdapter'

def test_case_27():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    str_0 = '6$I]hI\tiP!^X~'
    read_timeout_error_0 = module_3.ReadTimeoutError(str_0, str_0, str_0)
    h_t_t_p_adapter_0.build_connection_pool_key_attributes(read_timeout_error_0, str_0)

@pytest.mark.xfail(strict=True)
def test_case_28():
    bool_0 = False
    response_0 = module_1.Response()
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    h_t_t_p_adapter_0.get_connection_with_tls_context(response_0, bool_0, cert=bool_0)

def test_case_29():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    str_0 = ']'
    read_timeout_error_0 = module_3.ReadTimeoutError(str_0, str_0, str_0)
    h_t_t_p_adapter_0.build_connection_pool_key_attributes(read_timeout_error_0, str_0)

@pytest.mark.xfail(strict=True)
def test_case_30():
    h_t_t_p_adapter_0 = module_0.HTTPAdapter()
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    str_0 = 'J/oc\x0c'
    h_t_t_p_adapter_0.proxy_manager_for(str_0)

@pytest.mark.xfail(strict=True)
def test_case_31():
    response_0 = module_1.Response()
    h_t_t_p_adapter_0 = module_0.HTTPAdapter(pool_block=response_0)
    assert f'{type(h_t_t_p_adapter_0).__module__}.{type(h_t_t_p_adapter_0).__qualname__}' == 'requests.adapters.HTTPAdapter'
    assert f'{type(h_t_t_p_adapter_0.max_retries).__module__}.{type(h_t_t_p_adapter_0.max_retries).__qualname__}' == 'urllib3.util.retry.Retry'
    assert h_t_t_p_adapter_0.config == {}
    assert h_t_t_p_adapter_0.proxy_manager == {}
    assert f'{type(h_t_t_p_adapter_0.poolmanager).__module__}.{type(h_t_t_p_adapter_0.poolmanager).__qualname__}' == 'urllib3.poolmanager.PoolManager'
    assert module_0.DEFAULT_POOLSIZE == 10
    assert module_0.DEFAULT_RETRIES == 0
    str_0 = '&'
    url_0 = module_4.parse_url(str_0)
    h_t_t_p_adapter_0.send(response_0, cert=url_0, proxies=str_0)