# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import requests.help as module_0


def test_case_0():
    dict_0 = module_0.info()
    assert module_0.chardet is None
    assert module_0.pyopenssl is None
    assert module_0.OpenSSL is None
    assert module_0.cryptography is None
