# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import scaffold as module_0


def test_case_0():
    str_0 = "lB8)6-w\r'Sa"
    scaffold_0 = module_0.Scaffold(str_0, str_0)
    assert (
        f"{type(scaffold_0).__module__}.{type(scaffold_0).__qualname__}"
        == "flask.sansio.scaffold.Scaffold"
    )
    assert scaffold_0.import_name == "lB8)6-w\r'Sa"
    assert scaffold_0.template_folder is None
    assert scaffold_0.root_path == "F:\\Ky_5\\SWT301_Materials\\RT-SWT-nhom2"
    assert scaffold_0.view_functions == {}
    assert (
        f"{type(scaffold_0.error_handler_spec).__module__}.{type(scaffold_0.error_handler_spec).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.error_handler_spec) == 0
    assert (
        f"{type(scaffold_0.before_request_funcs).__module__}.{type(scaffold_0.before_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.before_request_funcs) == 0
    assert (
        f"{type(scaffold_0.after_request_funcs).__module__}.{type(scaffold_0.after_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.after_request_funcs) == 0
    assert (
        f"{type(scaffold_0.teardown_request_funcs).__module__}.{type(scaffold_0.teardown_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.teardown_request_funcs) == 0
    assert (
        f"{type(scaffold_0.template_context_processors).__module__}.{type(scaffold_0.template_context_processors).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.template_context_processors) == 1
    assert (
        f"{type(scaffold_0.url_value_preprocessors).__module__}.{type(scaffold_0.url_value_preprocessors).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.url_value_preprocessors) == 0
    assert (
        f"{type(scaffold_0.url_default_functions).__module__}.{type(scaffold_0.url_default_functions).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.url_default_functions) == 0
    assert (
        f"{type(module_0.Scaffold.static_folder).__module__}.{type(module_0.Scaffold.static_folder).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.has_static_folder).__module__}.{type(module_0.Scaffold.has_static_folder).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.static_url_path).__module__}.{type(module_0.Scaffold.static_url_path).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.jinja_loader).__module__}.{type(module_0.Scaffold.jinja_loader).__qualname__}"
        == "werkzeug.utils.cached_property"
    )
    assert module_0.Scaffold.jinja_loader.slot_name == "_cache_jinja_loader"


def test_case_1():
    str_0 = " "
    scaffold_0 = module_0.Scaffold(str_0)
    assert (
        f"{type(scaffold_0).__module__}.{type(scaffold_0).__qualname__}"
        == "flask.sansio.scaffold.Scaffold"
    )
    assert scaffold_0.import_name == " "
    assert scaffold_0.template_folder is None
    assert scaffold_0.root_path == "F:\\Ky_5\\SWT301_Materials\\RT-SWT-nhom2"
    assert scaffold_0.view_functions == {}
    assert (
        f"{type(scaffold_0.error_handler_spec).__module__}.{type(scaffold_0.error_handler_spec).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.error_handler_spec) == 0
    assert (
        f"{type(scaffold_0.before_request_funcs).__module__}.{type(scaffold_0.before_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.before_request_funcs) == 0
    assert (
        f"{type(scaffold_0.after_request_funcs).__module__}.{type(scaffold_0.after_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.after_request_funcs) == 0
    assert (
        f"{type(scaffold_0.teardown_request_funcs).__module__}.{type(scaffold_0.teardown_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.teardown_request_funcs) == 0
    assert (
        f"{type(scaffold_0.template_context_processors).__module__}.{type(scaffold_0.template_context_processors).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.template_context_processors) == 1
    assert (
        f"{type(scaffold_0.url_value_preprocessors).__module__}.{type(scaffold_0.url_value_preprocessors).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.url_value_preprocessors) == 0
    assert (
        f"{type(scaffold_0.url_default_functions).__module__}.{type(scaffold_0.url_default_functions).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.url_default_functions) == 0
    assert (
        f"{type(module_0.Scaffold.static_folder).__module__}.{type(module_0.Scaffold.static_folder).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.has_static_folder).__module__}.{type(module_0.Scaffold.has_static_folder).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.static_url_path).__module__}.{type(module_0.Scaffold.static_url_path).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.jinja_loader).__module__}.{type(module_0.Scaffold.jinja_loader).__qualname__}"
        == "werkzeug.utils.cached_property"
    )
    assert module_0.Scaffold.jinja_loader.slot_name == "_cache_jinja_loader"


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    str_0 = "lB8)6-w\r'Sa"
    scaffold_0 = module_0.Scaffold(str_0, str_0)
    assert (
        f"{type(scaffold_0).__module__}.{type(scaffold_0).__qualname__}"
        == "flask.sansio.scaffold.Scaffold"
    )
    assert scaffold_0.import_name == "lB8)6-w\r'Sa"
    assert scaffold_0.template_folder is None
    assert scaffold_0.root_path == "F:\\Ky_5\\SWT301_Materials\\RT-SWT-nhom2"
    assert scaffold_0.view_functions == {}
    assert (
        f"{type(scaffold_0.error_handler_spec).__module__}.{type(scaffold_0.error_handler_spec).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.error_handler_spec) == 0
    assert (
        f"{type(scaffold_0.before_request_funcs).__module__}.{type(scaffold_0.before_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.before_request_funcs) == 0
    assert (
        f"{type(scaffold_0.after_request_funcs).__module__}.{type(scaffold_0.after_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.after_request_funcs) == 0
    assert (
        f"{type(scaffold_0.teardown_request_funcs).__module__}.{type(scaffold_0.teardown_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.teardown_request_funcs) == 0
    assert (
        f"{type(scaffold_0.template_context_processors).__module__}.{type(scaffold_0.template_context_processors).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.template_context_processors) == 1
    assert (
        f"{type(scaffold_0.url_value_preprocessors).__module__}.{type(scaffold_0.url_value_preprocessors).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.url_value_preprocessors) == 0
    assert (
        f"{type(scaffold_0.url_default_functions).__module__}.{type(scaffold_0.url_default_functions).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.url_default_functions) == 0
    assert (
        f"{type(module_0.Scaffold.static_folder).__module__}.{type(module_0.Scaffold.static_folder).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.has_static_folder).__module__}.{type(module_0.Scaffold.has_static_folder).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.static_url_path).__module__}.{type(module_0.Scaffold.static_url_path).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.jinja_loader).__module__}.{type(module_0.Scaffold.jinja_loader).__qualname__}"
        == "werkzeug.utils.cached_property"
    )
    assert module_0.Scaffold.jinja_loader.slot_name == "_cache_jinja_loader"
    scaffold_0.route(bool_0)


def test_case_3():
    str_0 = " "
    scaffold_0 = module_0.Scaffold(
        str_0, static_url_path=str_0, template_folder=str_0, root_path=str_0
    )
    assert (
        f"{type(scaffold_0).__module__}.{type(scaffold_0).__qualname__}"
        == "flask.sansio.scaffold.Scaffold"
    )
    assert scaffold_0.import_name == " "
    assert scaffold_0.template_folder == " "
    assert scaffold_0.root_path == " "
    assert scaffold_0.view_functions == {}
    assert (
        f"{type(scaffold_0.error_handler_spec).__module__}.{type(scaffold_0.error_handler_spec).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.error_handler_spec) == 0
    assert (
        f"{type(scaffold_0.before_request_funcs).__module__}.{type(scaffold_0.before_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.before_request_funcs) == 0
    assert (
        f"{type(scaffold_0.after_request_funcs).__module__}.{type(scaffold_0.after_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.after_request_funcs) == 0
    assert (
        f"{type(scaffold_0.teardown_request_funcs).__module__}.{type(scaffold_0.teardown_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.teardown_request_funcs) == 0
    assert (
        f"{type(scaffold_0.template_context_processors).__module__}.{type(scaffold_0.template_context_processors).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.template_context_processors) == 1
    assert (
        f"{type(scaffold_0.url_value_preprocessors).__module__}.{type(scaffold_0.url_value_preprocessors).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.url_value_preprocessors) == 0
    assert (
        f"{type(scaffold_0.url_default_functions).__module__}.{type(scaffold_0.url_default_functions).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.url_default_functions) == 0
    assert (
        f"{type(module_0.Scaffold.static_folder).__module__}.{type(module_0.Scaffold.static_folder).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.has_static_folder).__module__}.{type(module_0.Scaffold.has_static_folder).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.static_url_path).__module__}.{type(module_0.Scaffold.static_url_path).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.jinja_loader).__module__}.{type(module_0.Scaffold.jinja_loader).__qualname__}"
        == "werkzeug.utils.cached_property"
    )
    assert module_0.Scaffold.jinja_loader.slot_name == "_cache_jinja_loader"


def test_case_4():
    str_0 = "lB8)6-w\r'Sa"
    module_0.find_package(str_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = "O,.N0(}pn:FsV"
    scaffold_0 = module_0.Scaffold(str_0)
    assert (
        f"{type(scaffold_0).__module__}.{type(scaffold_0).__qualname__}"
        == "flask.sansio.scaffold.Scaffold"
    )
    assert scaffold_0.import_name == "O,.N0(}pn:FsV"
    assert scaffold_0.template_folder is None
    assert scaffold_0.root_path == "F:\\Ky_5\\SWT301_Materials\\RT-SWT-nhom2"
    assert scaffold_0.view_functions == {}
    assert (
        f"{type(scaffold_0.error_handler_spec).__module__}.{type(scaffold_0.error_handler_spec).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.error_handler_spec) == 0
    assert (
        f"{type(scaffold_0.before_request_funcs).__module__}.{type(scaffold_0.before_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.before_request_funcs) == 0
    assert (
        f"{type(scaffold_0.after_request_funcs).__module__}.{type(scaffold_0.after_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.after_request_funcs) == 0
    assert (
        f"{type(scaffold_0.teardown_request_funcs).__module__}.{type(scaffold_0.teardown_request_funcs).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.teardown_request_funcs) == 0
    assert (
        f"{type(scaffold_0.template_context_processors).__module__}.{type(scaffold_0.template_context_processors).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.template_context_processors) == 1
    assert (
        f"{type(scaffold_0.url_value_preprocessors).__module__}.{type(scaffold_0.url_value_preprocessors).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.url_value_preprocessors) == 0
    assert (
        f"{type(scaffold_0.url_default_functions).__module__}.{type(scaffold_0.url_default_functions).__qualname__}"
        == "collections.defaultdict"
    )
    assert len(scaffold_0.url_default_functions) == 0
    assert (
        f"{type(module_0.Scaffold.static_folder).__module__}.{type(module_0.Scaffold.static_folder).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.has_static_folder).__module__}.{type(module_0.Scaffold.has_static_folder).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.static_url_path).__module__}.{type(module_0.Scaffold.static_url_path).__qualname__}"
        == "builtins.property"
    )
    assert (
        f"{type(module_0.Scaffold.jinja_loader).__module__}.{type(module_0.Scaffold.jinja_loader).__qualname__}"
        == "werkzeug.utils.cached_property"
    )
    assert module_0.Scaffold.jinja_loader.slot_name == "_cache_jinja_loader"
    scaffold_0.__repr__()


def test_case_6():
    str_0 = "6"
    module_0.find_package(str_0)


def test_case_7():
    str_0 = "M"
    module_0.find_package(str_0)


def test_case_8():
    str_0 = "&!YC}X1%R[rsQG"
    module_0.find_package(str_0)
