# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import requests.cookies as module_0
import urllib.request as module_1
import email._header_value_parser as module_2


def test_case_0():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    requests_cookie_jar_0.values()


def test_case_1():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    requests_cookie_jar_0.update(requests_cookie_jar_0)


def test_case_2():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    requests_cookie_jar_0.items()


@pytest.mark.xfail(strict=True)
def test_case_3():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    requests_cookie_jar_0.__setitem__(requests_cookie_jar_0, requests_cookie_jar_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    var_0 = module_1.ftperrors()
    module_0.MockRequest(var_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = "'~"
    module_0.get_cookie_header(str_0, str_0)


def test_case_6():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    requests_cookie_jar_0.__delitem__(requests_cookie_jar_0)


def test_case_7():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "\x0bmtgO"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    none_type_1 = requests_cookie_jar_0.__setitem__(str_0, none_type_0)
    assert len(requests_cookie_jar_0) == 0


@pytest.mark.xfail(strict=True)
def test_case_8():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    requests_cookie_jar_0.__getitem__(requests_cookie_jar_0)


def test_case_9():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    requests_cookie_jar_1 = requests_cookie_jar_0.copy()
    assert (
        f"{type(requests_cookie_jar_1).__module__}.{type(requests_cookie_jar_1).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_1) == 0


def test_case_10():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    requests_cookie_jar_0.keys()


def test_case_11():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    requests_cookie_jar_0.__setstate__(requests_cookie_jar_0)


def test_case_12():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    bool_0 = requests_cookie_jar_0.multiple_domains()
    assert bool_0 is False


def test_case_13():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "ZiyxHE"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    requests_cookie_jar_0.get_dict(path=none_type_0)


def test_case_14():
    none_type_0 = None
    cookie_jar_0 = module_0.cookiejar_from_dict(none_type_0, overwrite=none_type_0)
    assert (
        f"{type(cookie_jar_0).__module__}.{type(cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(cookie_jar_0) == 0


def test_case_15():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    cookie_jar_0 = module_0.cookiejar_from_dict(
        requests_cookie_jar_0, requests_cookie_jar_0
    )
    assert (
        f"{type(cookie_jar_0).__module__}.{type(cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(cookie_jar_0) == 0


def test_case_16():
    cookie_conflict_error_0 = module_0.CookieConflictError()
    mock_response_0 = module_0.MockResponse(cookie_conflict_error_0)
    mock_response_0.info()


@pytest.mark.xfail(strict=True)
def test_case_17():
    str_0 = "ou\x0c:@#(u"
    none_type_0 = None
    module_0.cookiejar_from_dict(str_0, overwrite=none_type_0)


def test_case_18():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    requests_cookie_jar_0.list_domains()


@pytest.mark.xfail(strict=True)
def test_case_19():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    module_0.morsel_to_cookie(requests_cookie_jar_0)


@pytest.mark.xfail(strict=True)
def test_case_20():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    none_type_0 = requests_cookie_jar_0.__delitem__(requests_cookie_jar_0)
    requests_cookie_jar_0.update(none_type_0)


def test_case_21():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "'~"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1


def test_case_22():
    str_0 = "pornEspecyfi>e6"
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
    none_type_0 = None
    cookie_jar_0 = module_0.cookiejar_from_dict(dict_0, none_type_0)
    assert (
        f"{type(cookie_jar_0).__module__}.{type(cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(cookie_jar_0) == 1


def test_case_23():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    cookie_jar_0 = module_0.merge_cookies(requests_cookie_jar_0, requests_cookie_jar_0)
    assert (
        f"{type(cookie_jar_0).__module__}.{type(cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(cookie_jar_0) == 0


def test_case_24():
    str_0 = "pornEspecyfi>e6"
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
    with pytest.raises(ValueError):
        module_0.merge_cookies(str_0, dict_0)


@pytest.mark.xfail(strict=True)
def test_case_25():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    none_type_0 = requests_cookie_jar_0.__delitem__(requests_cookie_jar_0)
    requests_cookie_jar_0.__getstate__()
    requests_cookie_jar_0.update(none_type_0)


def test_case_26():
    var_0 = module_1.ftperrors()
    module_0.extract_cookies_to_jar(var_0, var_0, var_0)


def test_case_27():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    requests_cookie_jar_0.get(requests_cookie_jar_0)


def test_case_28():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "ZiyxHE"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    requests_cookie_jar_0.get_dict(str_0, none_type_0)
    bool_0 = requests_cookie_jar_0.multiple_domains()
    assert bool_0 is False


@pytest.mark.xfail(strict=True)
def test_case_29():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "A user-created :class:Request%<Request>` object.>\n    Used to prepare a :class:`PreparedRequest <PreparedRequest>`, which is sent to the server.\n\n    :param method: HTTP method to use\n    :param url: URL to nd.\n    :param headers: dictionary of headers to send.\n    :param files: dictionary of {filBname: fileobject} files to multipart upload.\n    :param data: the body to attach 0o the request. If a dictioXary or\n       a?ist of tuples ``[(key, value)]`` is provided, form-encodin will\n        take place.\n    :param json: json for the body to attach to the r1qust (if files or data is not saecified).\n    :paam params: URL parametrs to append to the URL. If a dictionary or\n     ^  lisT of tuplks ``[(key, valuv)]`` is profided, form-encoding will\n        take place.\n    :param auth: Auh handlr or (user, pass) tuple.\n    :param cookies: dictionary or CookieJar of cookies to attach to this request.\n    :param hooks: dictionary of callback hooks, for internal usage.\n\n    Usage::\n\n      >>> import #eIuests\n      >>> req = requests.Request('GET', 'https://httpbin.org/get')\n      >>> req.prepare()\n     <PreparedRequest [GET]>\n    "
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    module_2.get_quoted_string(requests_cookie_jar_0)


def test_case_30():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "'~"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    requests_cookie_jar_0.list_domains()


def test_case_31():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    requests_cookie_jar_0.list_paths()
    requests_cookie_jar_0.values()


def test_case_32():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = ""
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    str_1 = "@|X;"
    requests_cookie_jar_0.__setitem__(str_1, none_type_0)
    requests_cookie_jar_1 = requests_cookie_jar_0.copy()
    assert (
        f"{type(requests_cookie_jar_1).__module__}.{type(requests_cookie_jar_1).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_1) == 1


def test_case_33():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "ZiyxHE"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1


def test_case_34():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = '"[K|'
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    requests_cookie_jar_0.list_domains()


def test_case_35():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = ""
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    requests_cookie_jar_0.__setstate__(requests_cookie_jar_0)


def test_case_36():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "'~"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    requests_cookie_jar_0.list_paths()


@pytest.mark.xfail(strict=True)
def test_case_37():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    none_type_0 = None
    cookie_jar_0 = module_0.merge_cookies(requests_cookie_jar_0, none_type_0)
    assert (
        f"{type(cookie_jar_0).__module__}.{type(cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(cookie_jar_0) == 0
    none_type_1 = None
    requests_cookie_jar_0.__setitem__(none_type_1, requests_cookie_jar_0)


def test_case_38():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = ""
    str_1 = ""
    none_type_0 = requests_cookie_jar_0.__setitem__(str_1, str_0)
    assert len(requests_cookie_jar_0) == 1
    requests_cookie_jar_0.list_domains()
    requests_cookie_jar_0.values()
    requests_cookie_jar_0.get(str_1, none_type_0, path=str_0)


def test_case_39():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "ZiyxHE"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    bool_0 = requests_cookie_jar_0.multiple_domains()
    assert bool_0 is False


def test_case_40():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "u:|x./"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    requests_cookie_jar_0.items()


def test_case_41():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "d!"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    requests_cookie_jar_0.get_dict(str_0, none_type_0)
    bool_0 = requests_cookie_jar_0.multiple_domains()
    assert bool_0 is False


@pytest.mark.xfail(strict=True)
def test_case_42():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "ZiyxHE"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    mock_response_0 = module_0.MockResponse(none_type_0)
    requests_cookie_jar_0.get_dict(path=none_type_0)
    str_1 = "JK"
    mock_response_0.getheaders(str_1)


@pytest.mark.xfail(strict=True)
def test_case_43():
    str_0 = ""
    str_1 = "=S3~E\x0byC#|uj0T\tG;"
    str_2 = "L(@"
    dict_0 = {str_1: str_1, str_2: str_1, str_2: str_2}
    module_0.create_cookie(str_0, str_0, **dict_0)


@pytest.mark.xfail(strict=True)
def test_case_44():
    var_0 = module_1.ftperrors()
    module_0.cookiejar_from_dict(var_0, var_0, var_0)


def test_case_45():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "ZiyxHE"
    str_1 = "t8+*"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_1, str_1)
    assert len(requests_cookie_jar_0) == 1
    requests_cookie_jar_0.get_dict(path=str_0)


def test_case_46():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "/"
    str_1 = "t8+*"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_1, str_1)
    assert len(requests_cookie_jar_0) == 1
    requests_cookie_jar_0.get_dict(path=str_0)


@pytest.mark.xfail(strict=True)
def test_case_47():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "!!.6(:zla*^2w"
    str_1 = "k|-b).xM}iZ(&K"
    var_0 = requests_cookie_jar_0.set(str_1, str_0)
    assert len(requests_cookie_jar_0) == 1
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "http.cookiejar.Cookie"
    )
    assert var_0.version == 0
    assert var_0.name == "k|-b).xM}iZ(&K"
    assert var_0.value == "!!.6(:zla*^2w"
    assert var_0.port is None
    assert var_0.port_specified is False
    assert var_0.domain == ""
    assert var_0.domain_specified is False
    assert var_0.domain_initial_dot is False
    assert var_0.path == "/"
    assert var_0.path_specified is True
    assert var_0.secure is False
    assert var_0.expires is None
    assert var_0.discard is True
    assert var_0.comment is None
    assert var_0.comment_url is None
    assert var_0.rfc2109 is False
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 2
    bool_0 = requests_cookie_jar_0.multiple_domains()
    assert bool_0 is True
    requests_cookie_jar_0.update(var_0)


def test_case_48():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "/"
    str_1 = ""
    none_type_0 = requests_cookie_jar_0.__setitem__(str_1, str_0)
    assert len(requests_cookie_jar_0) == 1
    requests_cookie_jar_0.list_domains()
    requests_cookie_jar_0.values()
    var_0 = requests_cookie_jar_0.get(str_1, none_type_0, path=str_0)
    assert var_0 == "/"


def test_case_49():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "/"
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    requests_cookie_jar_0.get(str_0, domain=requests_cookie_jar_0)


def test_case_50():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "7/F+Y UiS9o<\x0c4Hi"
    str_1 = ", path="
    str_2 = "F"
    requests_cookie_jar_0.values()
    str_3 = "\x0c"
    str_4 = "T2=Xg]skk\x0c4"
    dict_0 = {str_1: str_1, str_0: str_1, str_1: str_2, str_3: str_4}
    cookie_jar_0 = module_0.merge_cookies(requests_cookie_jar_0, dict_0)
    assert len(requests_cookie_jar_0) == 3
    assert (
        f"{type(cookie_jar_0).__module__}.{type(cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(cookie_jar_0) == 3


def test_case_51():
    requests_cookie_jar_0 = module_0.RequestsCookieJar()
    assert (
        f"{type(requests_cookie_jar_0).__module__}.{type(requests_cookie_jar_0).__qualname__}"
        == "requests.cookies.RequestsCookieJar"
    )
    assert len(requests_cookie_jar_0) == 0
    str_0 = "\x0c_"
    iterator_0 = requests_cookie_jar_0.iterkeys()
    none_type_0 = requests_cookie_jar_0.__setitem__(str_0, str_0)
    assert len(requests_cookie_jar_0) == 1
    var_0 = requests_cookie_jar_0.update(iterator_0)
    assert len(requests_cookie_jar_0) == 2
    requests_cookie_jar_0.list_domains()
