/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 04 02:48:46 GMT 2026
 */

package org.apache.commons.collections4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.nio.file.LinkOption;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.EnumSet;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;
import java.util.Locale;
import java.util.Map;
import java.util.PriorityQueue;
import java.util.ServiceLoader;
import java.util.SortedSet;
import java.util.Stack;
import java.util.StringTokenizer;
import java.util.TreeSet;
import java.util.Vector;
import org.apache.commons.collections4.BoundedCollection;
import org.apache.commons.collections4.Closure;
import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.collections4.Equator;
import org.apache.commons.collections4.Factory;
import org.apache.commons.collections4.Predicate;
import org.apache.commons.collections4.Transformer;
import org.apache.commons.collections4.collection.UnmodifiableBoundedCollection;
import org.apache.commons.collections4.functors.AllPredicate;
import org.apache.commons.collections4.functors.AnyPredicate;
import org.apache.commons.collections4.functors.ChainedClosure;
import org.apache.commons.collections4.functors.ChainedTransformer;
import org.apache.commons.collections4.functors.CloneTransformer;
import org.apache.commons.collections4.functors.ComparatorPredicate;
import org.apache.commons.collections4.functors.ConstantTransformer;
import org.apache.commons.collections4.functors.DefaultEquator;
import org.apache.commons.collections4.functors.EqualPredicate;
import org.apache.commons.collections4.functors.ExceptionClosure;
import org.apache.commons.collections4.functors.ExceptionFactory;
import org.apache.commons.collections4.functors.ExceptionTransformer;
import org.apache.commons.collections4.functors.FactoryTransformer;
import org.apache.commons.collections4.functors.FalsePredicate;
import org.apache.commons.collections4.functors.ForClosure;
import org.apache.commons.collections4.functors.IdentityPredicate;
import org.apache.commons.collections4.functors.InstanceofPredicate;
import org.apache.commons.collections4.functors.InvokerTransformer;
import org.apache.commons.collections4.functors.MapTransformer;
import org.apache.commons.collections4.functors.NOPClosure;
import org.apache.commons.collections4.functors.NullIsFalsePredicate;
import org.apache.commons.collections4.functors.NullPredicate;
import org.apache.commons.collections4.functors.OrPredicate;
import org.apache.commons.collections4.functors.TransformedPredicate;
import org.apache.commons.collections4.functors.TransformerClosure;
import org.apache.commons.collections4.functors.TransformerPredicate;
import org.apache.commons.collections4.functors.TruePredicate;
import org.apache.commons.collections4.functors.UniquePredicate;
import org.apache.commons.collections4.functors.WhileClosure;
import org.apache.commons.collections4.list.FixedSizeList;
import org.apache.commons.collections4.queue.CircularFifoQueue;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CollectionUtils_ESTest extends CollectionUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      ArrayDeque<ComparatorPredicate.Criterion> arrayDeque0 = new ArrayDeque<ComparatorPredicate.Criterion>();
      Iterator<ComparatorPredicate.Criterion> iterator0 = arrayDeque0.iterator();
      Integer integer0 = new Integer((-1682));
      ConstantTransformer<ComparatorPredicate.Criterion, Integer> constantTransformer0 = new ConstantTransformer<ComparatorPredicate.Criterion, Integer>(integer0);
      Collection<Integer> collection0 = CollectionUtils.collect(iterator0, (Transformer<? super ComparatorPredicate.Criterion, ? extends Integer>) constantTransformer0);
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      Collection<Integer> collection1 = CollectionUtils.union((Iterable<? extends Integer>) treeSet0, (Iterable<? extends Integer>) collection0);
      assertNotSame(collection0, collection1);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Integer integer0 = Integer.valueOf((int) (byte)53);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      HashMap<Integer, Integer> hashMap0 = new HashMap<Integer, Integer>();
      Transformer<Integer, Integer> transformer0 = MapTransformer.mapTransformer((Map<? super Integer, ? extends Integer>) hashMap0);
      Collection<Integer> collection0 = CollectionUtils.transformingCollection((Collection<Integer>) list0, (Transformer<? super Integer, ? extends Integer>) transformer0);
      assertTrue(collection0.contains(integer0));
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      PriorityQueue<Locale.IsoCountryCode> priorityQueue0 = new PriorityQueue<Locale.IsoCountryCode>();
      PriorityQueue<Locale.IsoCountryCode> priorityQueue1 = new PriorityQueue<Locale.IsoCountryCode>(priorityQueue0);
      Collection<Locale.IsoCountryCode> collection0 = CollectionUtils.subtract((Iterable<? extends Locale.IsoCountryCode>) priorityQueue1, (Iterable<? extends Locale.IsoCountryCode>) priorityQueue0);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      LinkedHashSet<Object> linkedHashSet0 = new LinkedHashSet<Object>();
      linkedHashSet0.add((Object) null);
      Integer integer0 = new Integer(1);
      EqualPredicate<Object> equalPredicate0 = new EqualPredicate<Object>(integer0);
      LinkedHashSet<Object> linkedHashSet1 = new LinkedHashSet<Object>();
      CollectionUtils.select((Iterable<?>) linkedHashSet0, (Predicate<? super Object>) equalPredicate0, linkedHashSet0, linkedHashSet1);
      assertEquals(1, linkedHashSet1.size());
      assertTrue(linkedHashSet0.equals((Object)linkedHashSet1));
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      PriorityQueue<LinkedList<Integer>> priorityQueue0 = new PriorityQueue<LinkedList<Integer>>(1000);
      Vector<Comparable<Object>> vector0 = new Vector<Comparable<Object>>(1000);
      Collection<Comparable<Object>> collection0 = CollectionUtils.retainAll((Collection<Comparable<Object>>) vector0, (Collection<?>) priorityQueue0);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      ArrayDeque<Integer> arrayDeque0 = new ArrayDeque<Integer>();
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      Collection<Integer> collection0 = CollectionUtils.removeAll((Collection<Integer>) arrayDeque0, (Collection<?>) treeSet0);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      ArrayDeque<LinkedHashSet<Integer>> arrayDeque0 = new ArrayDeque<LinkedHashSet<Integer>>();
      int int0 = CollectionUtils.maxSize(arrayDeque0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      HashSet<Integer> hashSet0 = new HashSet<Integer>();
      Collection<Integer> collection0 = CollectionUtils.unmodifiableCollection((Collection<? extends Integer>) hashSet0);
      DefaultEquator<Integer> defaultEquator0 = DefaultEquator.defaultEquator();
      boolean boolean0 = CollectionUtils.isEqualCollection((Collection<? extends Integer>) hashSet0, (Collection<? extends Integer>) collection0, (Equator<? super Integer>) defaultEquator0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Predicate<Object> predicate0 = FalsePredicate.falsePredicate();
      NullIsFalsePredicate<Integer> nullIsFalsePredicate0 = new NullIsFalsePredicate<Integer>(predicate0);
      // Undeclared exception!
      try { 
        CollectionUtils.get((Object) nullIsFalsePredicate0, 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported object type: org.apache.commons.collections4.functors.NullIsFalsePredicate
         //
         verifyException("org.apache.commons.collections4.CollectionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      TreeSet<LinkOption> treeSet0 = new TreeSet<LinkOption>();
      TreeSet<LinkOption> treeSet1 = new TreeSet<LinkOption>((SortedSet<LinkOption>) treeSet0);
      Collection<LinkOption> collection0 = CollectionUtils.disjunction((Iterable<? extends LinkOption>) treeSet1, (Iterable<? extends LinkOption>) treeSet0);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      ArrayList<InstanceofPredicate> arrayList0 = new ArrayList<InstanceofPredicate>();
      boolean boolean0 = CollectionUtils.containsAny((Collection<?>) treeSet0, (Collection<?>) arrayList0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      ArrayList<Integer> arrayList0 = new ArrayList<Integer>();
      Collection<Integer> collection0 = CollectionUtils.intersection((Iterable<? extends Integer>) arrayList0, (Iterable<? extends Integer>) arrayList0);
      List<Integer> list0 = CollectionUtils.collate((Iterable<? extends Integer>) collection0, (Iterable<? extends Integer>) arrayList0, false);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      PriorityQueue<LinkOption> priorityQueue0 = new PriorityQueue<LinkOption>();
      LinkOption[] linkOptionArray0 = new LinkOption[5];
      LinkOption linkOption0 = LinkOption.NOFOLLOW_LINKS;
      linkOptionArray0[0] = linkOption0;
      linkOptionArray0[1] = linkOptionArray0[0];
      // Undeclared exception!
      try { 
        CollectionUtils.addAll((Collection<LinkOption>) priorityQueue0, linkOptionArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.PriorityQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      TreeSet<LinkOption> treeSet0 = new TreeSet<LinkOption>();
      TreeSet<LinkOption> treeSet1 = new TreeSet<LinkOption>((SortedSet<LinkOption>) treeSet0);
      Collection<LinkOption> collection0 = CollectionUtils.intersection((Iterable<? extends LinkOption>) treeSet1, (Iterable<? extends LinkOption>) treeSet0);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      CollectionUtils.checkIndexBounds(1615);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      ArrayList<Collection<Locale.Category>> arrayList0 = new ArrayList<Collection<Locale.Category>>();
      // Undeclared exception!
      try { 
        CollectionUtils.addAll((Collection<Collection<Locale.Category>>) arrayList0, (Enumeration<? extends Collection<Locale.Category>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // enumeration
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      LinkedHashSet<Object> linkedHashSet0 = new LinkedHashSet<Object>();
      linkedHashSet0.add((Object) null);
      int int0 = CollectionUtils.size(linkedHashSet0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      HashSet<Object> hashSet0 = new HashSet<Object>(1291);
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      List<Object> list0 = CollectionUtils.collate((Iterable<?>) hashSet0, (Iterable<?>) hashSet0, (Comparator<? super Object>) comparator0);
      hashSet0.add((Object) null);
      FixedSizeList<Object> fixedSizeList0 = FixedSizeList.fixedSizeList(list0);
      boolean boolean0 = CollectionUtils.isEqualCollection((Collection<?>) fixedSizeList0, (Collection<?>) hashSet0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Predicate<Object> predicate0 = TruePredicate.truePredicate();
      LinkedHashSet<LinkOption> linkedHashSet0 = new LinkedHashSet<LinkOption>();
      List<LinkedHashSet<LinkOption>> list0 = List.of(linkedHashSet0, linkedHashSet0, linkedHashSet0, linkedHashSet0, linkedHashSet0, linkedHashSet0, linkedHashSet0, linkedHashSet0);
      int int0 = CollectionUtils.countMatches((Iterable<LinkedHashSet<LinkOption>>) list0, (Predicate<? super LinkedHashSet<LinkOption>>) predicate0);
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Integer integer0 = Integer.valueOf((int) (byte)53);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Comparator<Comparable<Integer>> comparator0 = (Comparator<Comparable<Integer>>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      doReturn(0, 0, 0, 0, 0).when(comparator0).compare(any(java.lang.Comparable.class) , any(java.lang.Comparable.class));
      List<Comparable<Integer>> list1 = CollectionUtils.collate((Iterable<? extends Comparable<Integer>>) list0, (Iterable<? extends Comparable<Integer>>) list0, (Comparator<? super Comparable<Integer>>) comparator0);
      assertEquals(14, list1.size());
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      PriorityQueue<LinkOption> priorityQueue0 = new PriorityQueue<LinkOption>();
      LinkOption linkOption0 = LinkOption.NOFOLLOW_LINKS;
      priorityQueue0.add(linkOption0);
      List<LinkOption> list0 = CollectionUtils.collate((Iterable<? extends LinkOption>) priorityQueue0, (Iterable<? extends LinkOption>) priorityQueue0);
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      List<Object> list0 = List.of();
      Locale.IsoCountryCode locale_IsoCountryCode0 = Locale.IsoCountryCode.PART1_ALPHA2;
      int int0 = CollectionUtils.cardinality(locale_IsoCountryCode0, (Iterable<? super Locale.IsoCountryCode>) list0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      CircularFifoQueue<LinkOption> circularFifoQueue0 = new CircularFifoQueue<LinkOption>();
      LinkOption[] linkOptionArray0 = new LinkOption[1];
      LinkOption linkOption0 = LinkOption.NOFOLLOW_LINKS;
      linkOptionArray0[0] = linkOption0;
      boolean boolean0 = CollectionUtils.addAll((Collection<LinkOption>) circularFifoQueue0, linkOptionArray0);
      assertEquals(1, circularFifoQueue0.size());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Stack<Object> stack0 = new Stack<Object>();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.IGNORE_EXTENDED_RANGES;
      stack0.add((Object) locale_FilteringMode0);
      boolean boolean0 = CollectionUtils.addAll((Collection<Object>) stack0, (Iterable<?>) stack0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.unmodifiableCollection((Collection<? extends Closure<Object>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // collection
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.union((Iterable<? extends Integer>) null, (Iterable<? extends Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // a
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      LinkedHashSet<LinkOption> linkedHashSet0 = new LinkedHashSet<LinkOption>();
      List<LinkedHashSet<LinkOption>> list0 = List.of(linkedHashSet0);
      // Undeclared exception!
      try { 
        CollectionUtils.transformingCollection((Collection<LinkedHashSet<LinkOption>>) list0, (Transformer<? super LinkedHashSet<LinkOption>, ? extends LinkedHashSet<LinkOption>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // transformer
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      ArrayDeque<ComparatorPredicate.Criterion> arrayDeque0 = new ArrayDeque<ComparatorPredicate.Criterion>();
      Iterator<ComparatorPredicate.Criterion> iterator0 = arrayDeque0.iterator();
      Integer integer0 = new Integer((-1682));
      ConstantTransformer<ComparatorPredicate.Criterion, Integer> constantTransformer0 = new ConstantTransformer<ComparatorPredicate.Criterion, Integer>(integer0);
      Collection<Integer> collection0 = CollectionUtils.collect(iterator0, (Transformer<? super ComparatorPredicate.Criterion, ? extends Integer>) constantTransformer0);
      // Undeclared exception!
      try { 
        CollectionUtils.subtract((Iterable<?>) arrayDeque0, (Iterable<?>) collection0, (Predicate<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // p
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.subtract((Iterable<? extends Integer>) null, (Iterable<? extends Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // a
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      TransformerPredicate<Object> transformerPredicate0 = new TransformerPredicate<Object>((Transformer<? super Object, Boolean>) null);
      Predicate<Locale.FilteringMode> predicate0 = NullIsFalsePredicate.nullIsFalsePredicate((Predicate<? super Locale.FilteringMode>) transformerPredicate0);
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.MAP_EXTENDED_RANGES;
      Locale.FilteringMode[] locale_FilteringModeArray0 = new Locale.FilteringMode[3];
      locale_FilteringModeArray0[0] = locale_FilteringMode0;
      locale_FilteringModeArray0[1] = locale_FilteringMode0;
      locale_FilteringModeArray0[2] = locale_FilteringMode0;
      EnumSet<Locale.FilteringMode> enumSet0 = EnumSet.of(locale_FilteringMode0, locale_FilteringModeArray0);
      // Undeclared exception!
      try { 
        CollectionUtils.selectRejected((Iterable<? extends Locale.FilteringMode>) enumSet0, (Predicate<? super Locale.FilteringMode>) predicate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.functors.TransformerPredicate", e);
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      LinkedHashSet<Object> linkedHashSet0 = new LinkedHashSet<Object>();
      linkedHashSet0.add(linkedHashSet0);
      Predicate<Object> predicate0 = UniquePredicate.uniquePredicate();
      // Undeclared exception!
      try { 
        CollectionUtils.select((Iterable<?>) linkedHashSet0, (Predicate<? super Object>) predicate0, linkedHashSet0, linkedHashSet0);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Integer integer0 = new Integer(1295);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Transformer<Integer, Integer> transformer0 = ExceptionTransformer.exceptionTransformer();
      Comparator<Integer> comparator0 = (Comparator<Integer>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      Predicate<Integer> predicate0 = ComparatorPredicate.comparatorPredicate(integer0, comparator0);
      Predicate<Integer> predicate1 = TransformedPredicate.transformedPredicate((Transformer<? super Integer, ? extends Integer>) transformer0, (Predicate<? super Integer>) predicate0);
      // Undeclared exception!
      try { 
        CollectionUtils.select((Iterable<? extends Integer>) list0, (Predicate<? super Integer>) predicate1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // ExceptionTransformer invoked
         //
         verifyException("org.apache.commons.collections4.functors.ExceptionTransformer", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Integer integer0 = new Integer(1137);
      List<Integer> list0 = List.of(integer0);
      OrPredicate<Integer> orPredicate0 = new OrPredicate<Integer>((Predicate<? super Integer>) null, (Predicate<? super Integer>) null);
      // Undeclared exception!
      try { 
        CollectionUtils.select((Iterable<? extends Integer>) list0, (Predicate<? super Integer>) orPredicate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.functors.OrPredicate", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.reverseArray((Object[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // array
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.retainAll((Collection<Predicate<Object>>) null, (Collection<?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // collection
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      DefaultEquator<Integer> defaultEquator0 = DefaultEquator.defaultEquator();
      // Undeclared exception!
      try { 
        CollectionUtils.retainAll((Iterable<Integer>) null, (Iterable<? extends Integer>) null, (Equator<? super Integer>) defaultEquator0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // collection
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.removeRange((Collection<Object>) null, (-271), 2626);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // input
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.removeCount((Collection<LinkedList<Integer>>) null, (-271), (-271));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // input
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.removeAll((Collection<Integer>) null, (Collection<?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // collection
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      DefaultEquator<Integer> defaultEquator0 = DefaultEquator.defaultEquator();
      // Undeclared exception!
      try { 
        CollectionUtils.removeAll((Iterable<Integer>) null, (Iterable<? extends Integer>) null, (Equator<? super Integer>) defaultEquator0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // collection
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Predicate<Object>[] predicateArray0 = (Predicate<Object>[]) Array.newInstance(Predicate.class, 0);
      AllPredicate<Object> allPredicate0 = new AllPredicate<Object>(predicateArray0);
      // Undeclared exception!
      try { 
        CollectionUtils.predicatedCollection((Collection<Object>) null, (Predicate<? super Object>) allPredicate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // collection
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.permutations((Collection<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // collection
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.maxSize((Collection<?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // collection
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Integer integer0 = new Integer(1137);
      List<Integer> list0 = List.of(integer0);
      // Undeclared exception!
      try { 
        CollectionUtils.isSubCollection((Collection<?>) null, list0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // a
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.isProperSubCollection((Collection<?>) null, (Collection<?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // a
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      CircularFifoQueue<Object> circularFifoQueue0 = new CircularFifoQueue<Object>();
      TreeSet<Object> treeSet0 = new TreeSet<Object>(circularFifoQueue0);
      // Undeclared exception!
      try { 
        CollectionUtils.isEqualCollection((Collection<?>) treeSet0, (Collection<?>) circularFifoQueue0, (Equator<? super Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // equator
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      // Undeclared exception!
      try { 
        CollectionUtils.intersection((Iterable<? extends Integer>) null, (Iterable<? extends Integer>) treeSet0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // a
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.get((Iterator<WhileClosure<Object>>) null, 16);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // iterator
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      PriorityQueue<Integer> priorityQueue0 = new PriorityQueue<Integer>();
      DefaultEquator<Integer> defaultEquator0 = DefaultEquator.defaultEquator();
      Collection<Integer> collection0 = CollectionUtils.retainAll((Iterable<Integer>) priorityQueue0, (Iterable<? extends Integer>) priorityQueue0, (Equator<? super Integer>) defaultEquator0);
      // Undeclared exception!
      try { 
        CollectionUtils.get((Object) collection0, 1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.get((Iterable<Object>) null, (-1));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // iterable
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Iterator<ComparatorPredicate.Criterion> iterator0 = (Iterator<ComparatorPredicate.Criterion>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(iterator0).hasNext();
      Factory<Integer> factory0 = ExceptionFactory.exceptionFactory();
      FactoryTransformer<ComparatorPredicate.Criterion, Integer> factoryTransformer0 = new FactoryTransformer<ComparatorPredicate.Criterion, Integer>(factory0);
      Collection<Integer> collection0 = CollectionUtils.collect(iterator0, (Transformer<? super ComparatorPredicate.Criterion, ? extends Integer>) factoryTransformer0);
      // Undeclared exception!
      try { 
        CollectionUtils.get((Iterable<Integer>) collection0, 17);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Vector<Integer> vector0 = new Vector<Integer>(4);
      Integer integer0 = new Integer(14);
      vector0.add(integer0);
      Class<Locale.IsoCountryCode>[] classArray0 = (Class<Locale.IsoCountryCode>[]) Array.newInstance(Class.class, 0);
      Transformer<Integer, Integer> transformer0 = InvokerTransformer.invokerTransformer("PjYbrNEuw4:hO+<", (Class<?>[]) classArray0, (Object[]) classArray0);
      TransformerClosure<Integer> transformerClosure0 = new TransformerClosure<Integer>(transformer0);
      // Undeclared exception!
      try { 
        CollectionUtils.forAllDo((Iterable<Integer>) vector0, transformerClosure0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // InvokerTransformer: The method 'PjYbrNEuw4:hO+<' on 'class java.lang.Integer' does not exist
         //
         verifyException("org.apache.commons.collections4.functors.InvokerTransformer", e);
      }
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Predicate<Object> predicate0 = TruePredicate.truePredicate();
      List<Predicate<Object>> list0 = List.of(predicate0, predicate0, predicate0, predicate0, predicate0);
      ForClosure<Object> forClosure0 = new ForClosure<Object>(1295, (Closure<? super Object>) null);
      // Undeclared exception!
      try { 
        CollectionUtils.forAllButLastDo((Iterable<Predicate<Object>>) list0, forClosure0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.functors.ForClosure", e);
      }
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      AllPredicate<Object> allPredicate0 = new AllPredicate<Object>((Predicate<? super Object>[]) null);
      Integer integer0 = new Integer(2436);
      List<Integer> list0 = List.of(integer0);
      // Undeclared exception!
      try { 
        CollectionUtils.find((Iterable<Integer>) list0, (Predicate<? super Integer>) allPredicate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.functors.AllPredicate", e);
      }
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Integer integer0 = new Integer(1295);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Transformer<Integer, Integer> transformer0 = ExceptionTransformer.exceptionTransformer();
      Comparator<Integer> comparator0 = (Comparator<Integer>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      Predicate<Integer> predicate0 = ComparatorPredicate.comparatorPredicate(integer0, comparator0);
      Predicate<Integer> predicate1 = TransformedPredicate.transformedPredicate((Transformer<? super Integer, ? extends Integer>) transformer0, (Predicate<? super Integer>) predicate0);
      // Undeclared exception!
      try { 
        CollectionUtils.filter((Iterable<Integer>) list0, (Predicate<? super Integer>) predicate1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // ExceptionTransformer invoked
         //
         verifyException("org.apache.commons.collections4.functors.ExceptionTransformer", e);
      }
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Locale.Category locale_Category0 = Locale.Category.FORMAT;
      List<Locale.Category> list0 = List.of(locale_Category0, locale_Category0);
      Locale.Category locale_Category1 = Locale.Category.DISPLAY;
      IdentityPredicate<Locale.Category> identityPredicate0 = new IdentityPredicate<Locale.Category>(locale_Category1);
      // Undeclared exception!
      try { 
        CollectionUtils.filter((Iterable<Locale.Category>) list0, (Predicate<? super Locale.Category>) identityPredicate0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ImmutableCollections", e);
      }
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.extractSingleton((Collection<Collection<Object>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // collection
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.disjunction((Iterable<?>) null, (Iterable<?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // a
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.containsAny((Collection<?>) null, (Integer[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // coll1
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.containsAll((Collection<?>) null, (Collection<?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // coll1
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Locale.Category locale_Category0 = Locale.Category.DISPLAY;
      EnumSet<Locale.Category> enumSet0 = EnumSet.range(locale_Category0, locale_Category0);
      Iterator<Locale.Category> iterator0 = enumSet0.iterator();
      Transformer<Locale.Category, Integer> transformer0 = ExceptionTransformer.exceptionTransformer();
      // Undeclared exception!
      try { 
        CollectionUtils.collect(iterator0, (Transformer<? super Locale.Category, ? extends Integer>) transformer0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // ExceptionTransformer invoked
         //
         verifyException("org.apache.commons.collections4.functors.ExceptionTransformer", e);
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      PriorityQueue<LinkOption> priorityQueue0 = new PriorityQueue<LinkOption>();
      LinkOption linkOption0 = LinkOption.NOFOLLOW_LINKS;
      priorityQueue0.add(linkOption0);
      Transformer<Object, Object>[] transformerArray0 = (Transformer<Object, Object>[]) Array.newInstance(Transformer.class, 0);
      Transformer<Object, Object> transformer0 = ChainedTransformer.chainedTransformer((Transformer<? super Object, ?>[]) transformerArray0);
      // Undeclared exception!
      try { 
        CollectionUtils.collect((Iterable<?>) priorityQueue0, (Transformer<? super Object, ?>) transformer0, (Collection<Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.CollectionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.collate((Iterable<? extends Charset>) null, (Iterable<? extends Charset>) null, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // iterableA
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Comparator<InstanceofPredicate> comparator0 = (Comparator<InstanceofPredicate>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        CollectionUtils.collate((Iterable<? extends InstanceofPredicate>) null, (Iterable<? extends InstanceofPredicate>) null, (Comparator<? super InstanceofPredicate>) comparator0, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // iterableA
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      PriorityQueue<LinkOption> priorityQueue0 = new PriorityQueue<LinkOption>();
      // Undeclared exception!
      try { 
        CollectionUtils.collate((Iterable<? extends LinkOption>) priorityQueue0, (Iterable<? extends LinkOption>) priorityQueue0, (Comparator<? super LinkOption>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // comparator
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Collection<Integer> collection0 = CollectionUtils.emptyCollection();
      // Undeclared exception!
      try { 
        CollectionUtils.collate((Iterable<? extends Integer>) collection0, (Iterable<? extends Integer>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // iterableB
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      CircularFifoQueue<Integer> circularFifoQueue0 = new CircularFifoQueue<Integer>();
      // Undeclared exception!
      try { 
        CollectionUtils.cardinality((Object) circularFifoQueue0, (Iterable<? super Object>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // collection
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      CircularFifoQueue<LinkOption> circularFifoQueue0 = new CircularFifoQueue<LinkOption>();
      BoundedCollection<LinkOption> boundedCollection0 = UnmodifiableBoundedCollection.unmodifiableBoundedCollection((BoundedCollection<? extends LinkOption>) circularFifoQueue0);
      LinkOption[] linkOptionArray0 = new LinkOption[1];
      // Undeclared exception!
      try { 
        CollectionUtils.addAll((Collection<LinkOption>) boundedCollection0, linkOptionArray0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.collection.UnmodifiableBoundedCollection", e);
      }
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      LinkedHashSet<Locale.IsoCountryCode> linkedHashSet0 = new LinkedHashSet<Locale.IsoCountryCode>(31);
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      PriorityQueue<Closure<Object>> priorityQueue0 = new PriorityQueue<Closure<Object>>(comparator0);
      Collection<Object> collection0 = CollectionUtils.unmodifiableCollection((Collection<?>) linkedHashSet0);
      // Undeclared exception!
      try { 
        CollectionUtils.addAll(collection0, (Iterable<?>) priorityQueue0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.collection.UnmodifiableCollection", e);
      }
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Stack<Object> stack0 = new Stack<Object>();
      // Undeclared exception!
      try { 
        CollectionUtils.addAll((Collection<Object>) stack0, (Iterable<?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // iterable
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      PriorityQueue<LinkOption> priorityQueue0 = new PriorityQueue<LinkOption>();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.REJECT_EXTENDED_RANGES;
      EnumSet<Locale.FilteringMode> enumSet0 = EnumSet.of(locale_FilteringMode0, locale_FilteringMode0, locale_FilteringMode0, locale_FilteringMode0);
      enumSet0.retainAll(priorityQueue0);
      AnyPredicate<Locale.FilteringMode> anyPredicate0 = new AnyPredicate<Locale.FilteringMode>((Predicate<? super Locale.FilteringMode>[]) null);
      Collection<Locale.FilteringMode> collection0 = CollectionUtils.select((Iterable<? extends Locale.FilteringMode>) enumSet0, (Predicate<? super Locale.FilteringMode>) anyPredicate0, (Collection<Locale.FilteringMode>) enumSet0);
      assertFalse(collection0.contains(locale_FilteringMode0));
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.REJECT_EXTENDED_RANGES;
      EnumSet<Locale.FilteringMode> enumSet0 = EnumSet.of(locale_FilteringMode0, locale_FilteringMode0, locale_FilteringMode0, locale_FilteringMode0);
      AnyPredicate<Locale.FilteringMode> anyPredicate0 = new AnyPredicate<Locale.FilteringMode>((Predicate<? super Locale.FilteringMode>[]) null);
      // Undeclared exception!
      try { 
        CollectionUtils.select((Iterable<? extends Locale.FilteringMode>) enumSet0, (Predicate<? super Locale.FilteringMode>) anyPredicate0, (Collection<Locale.FilteringMode>) enumSet0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.functors.AnyPredicate", e);
      }
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Integer integer0 = new Integer(1295);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      boolean boolean0 = CollectionUtils.isEmpty(list0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      PriorityQueue<LinkOption> priorityQueue0 = new PriorityQueue<LinkOption>();
      Integer integer0 = new Integer((-522));
      Stack<Integer> stack0 = new Stack<Integer>();
      stack0.add(integer0);
      FactoryTransformer<Integer, LinkOption> factoryTransformer0 = new FactoryTransformer<Integer, LinkOption>((Factory<? extends LinkOption>) null);
      FixedSizeList<Integer> fixedSizeList0 = FixedSizeList.fixedSizeList((List<Integer>) stack0);
      ListIterator<Integer> listIterator0 = fixedSizeList0.listIterator();
      // Undeclared exception!
      try { 
        CollectionUtils.collect((Iterator<? extends Integer>) listIterator0, (Transformer<? super Integer, ? extends LinkOption>) factoryTransformer0, (Collection<LinkOption>) priorityQueue0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.collections4.functors.FactoryTransformer", e);
      }
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      PriorityQueue<LinkOption> priorityQueue0 = new PriorityQueue<LinkOption>();
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Iterator<Integer> iterator0 = linkedList0.descendingIterator();
      FactoryTransformer<Integer, LinkOption> factoryTransformer0 = new FactoryTransformer<Integer, LinkOption>((Factory<? extends LinkOption>) null);
      Collection<LinkOption> collection0 = CollectionUtils.collect((Iterator<? extends Integer>) iterator0, (Transformer<? super Integer, ? extends LinkOption>) factoryTransformer0, (Collection<LinkOption>) priorityQueue0);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      CircularFifoQueue<Integer> circularFifoQueue0 = new CircularFifoQueue<Integer>(1137);
      Transformer<Integer, Integer> transformer0 = InvokerTransformer.invokerTransformer("|e;o{JX@)DIP", (Class<?>[]) null, (Object[]) null);
      Collection<Integer> collection0 = CollectionUtils.collect((Iterable<Integer>) circularFifoQueue0, (Transformer<? super Integer, ? extends Integer>) transformer0);
      assertFalse(collection0.contains(1137));
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Collection<Locale.FilteringMode> collection0 = CollectionUtils.emptyCollection();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.MAP_EXTENDED_RANGES;
      ConstantTransformer<Object, Locale.FilteringMode> constantTransformer0 = new ConstantTransformer<Object, Locale.FilteringMode>(locale_FilteringMode0);
      Collection<Locale.FilteringMode> collection1 = CollectionUtils.collect((Iterable<? extends Comparable<Locale.FilteringMode>>) collection0, (Transformer<? super Comparable<Locale.FilteringMode>, ? extends Locale.FilteringMode>) constantTransformer0, collection0);
      assertSame(collection0, collection1);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Integer integer0 = new Integer(2626);
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      treeSet0.add(integer0);
      Comparator<Integer> comparator0 = (Comparator<Integer>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      doReturn(1).when(comparator0).compare(anyInt() , anyInt());
      List<Integer> list0 = CollectionUtils.collate((Iterable<? extends Integer>) treeSet0, (Iterable<? extends Integer>) treeSet0, (Comparator<? super Integer>) comparator0, false);
      assertTrue(list0.contains(2626));
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      Class<Integer> class0 = Integer.class;
      ServiceLoader<Integer> serviceLoader0 = ServiceLoader.load(class0);
      List<Integer> list0 = CollectionUtils.collate((Iterable<? extends Integer>) serviceLoader0, (Iterable<? extends Integer>) treeSet0, (Comparator<? super Integer>) comparator0, true);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      ArrayDeque<Integer> arrayDeque0 = new ArrayDeque<Integer>();
      Iterator<Integer> iterator0 = arrayDeque0.iterator();
      boolean boolean0 = CollectionUtils.addAll((Collection<Integer>) arrayDeque0, (Iterator<? extends Integer>) iterator0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      LinkedHashSet<Integer> linkedHashSet0 = new LinkedHashSet<Integer>();
      boolean boolean0 = CollectionUtils.addAll((Collection<Integer>) linkedHashSet0, (Iterable<? extends Integer>) linkedHashSet0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      HashSet<Object> hashSet0 = new HashSet<Object>(1291);
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      List<Object> list0 = CollectionUtils.collate((Iterable<?>) hashSet0, (Iterable<?>) hashSet0, (Comparator<? super Object>) comparator0);
      FixedSizeList<Object> fixedSizeList0 = FixedSizeList.fixedSizeList(list0);
      boolean boolean0 = CollectionUtils.isEqualCollection((Collection<?>) fixedSizeList0, (Collection<?>) hashSet0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      ArrayList<MockFile> arrayList0 = new ArrayList<MockFile>();
      Transformer<Object, MockFile> transformer0 = ExceptionTransformer.exceptionTransformer();
      MockFile mockFile0 = new MockFile("");
      arrayList0.add(mockFile0);
      // Undeclared exception!
      try { 
        CollectionUtils.transform((Collection<MockFile>) arrayList0, (Transformer<? super MockFile, ? extends MockFile>) transformer0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // ExceptionTransformer invoked
         //
         verifyException("org.apache.commons.collections4.functors.ExceptionTransformer", e);
      }
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      CircularFifoQueue<LinkedHashSet<Integer>> circularFifoQueue0 = new CircularFifoQueue<LinkedHashSet<Integer>>(512);
      Transformer<Object, LinkedHashSet<Integer>> transformer0 = InvokerTransformer.invokerTransformer("org.apache.commons.collections4.functors.FactoryTransformer");
      CollectionUtils.transform((Collection<LinkedHashSet<Integer>>) circularFifoQueue0, (Transformer<? super LinkedHashSet<Integer>, ? extends LinkedHashSet<Integer>>) transformer0);
      assertFalse(circularFifoQueue0.isFull());
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      CircularFifoQueue<Integer> circularFifoQueue0 = new CircularFifoQueue<Integer>();
      CollectionUtils.transform((Collection<Integer>) circularFifoQueue0, (Transformer<? super Integer, ? extends Integer>) null);
      assertFalse(circularFifoQueue0.isFull());
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      FactoryTransformer<Object, Object> factoryTransformer0 = new FactoryTransformer<Object, Object>((Factory<?>) null);
      CollectionUtils.transform((Collection<Object>) linkedList0, (Transformer<? super Object, ?>) factoryTransformer0);
      assertEquals(0, linkedList0.size());
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      CollectionUtils.transform((Collection<ByteBuffer>) null, (Transformer<? super ByteBuffer, ? extends ByteBuffer>) null);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Integer integer0 = new Integer((-1682));
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Predicate<Integer> predicate0 = EqualPredicate.equalPredicate((Integer) null, (Equator<Integer>) null);
      Collection<Integer> collection0 = CollectionUtils.subtract((Iterable<? extends Integer>) list0, (Iterable<? extends Integer>) list0, predicate0);
      assertTrue(collection0.contains((-1682)));
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      Integer integer0 = new Integer(2626);
      treeSet0.add(integer0);
      ArrayList<InstanceofPredicate> arrayList0 = new ArrayList<InstanceofPredicate>();
      Predicate<Integer> predicate0 = AllPredicate.allPredicate((Collection<? extends Predicate<? super Integer>>) arrayList0);
      Collection<Integer> collection0 = CollectionUtils.subtract((Iterable<? extends Integer>) treeSet0, (Iterable<? extends Integer>) treeSet0, predicate0);
      Collection<Object> collection1 = CollectionUtils.disjunction((Iterable<?>) collection0, (Iterable<?>) treeSet0);
      assertTrue(collection1.contains(2626));
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      boolean boolean0 = CollectionUtils.sizeIsEmpty((Object) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        CollectionUtils.sizeIsEmpty(object0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported object type: java.lang.Object
         //
         verifyException("org.apache.commons.collections4.CollectionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      LinkedHashSet<Object> linkedHashSet0 = new LinkedHashSet<Object>();
      int int0 = CollectionUtils.size(linkedHashSet0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      int int0 = CollectionUtils.size((Object) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Integer integer0 = new Integer((-1682));
      ConstantTransformer<ComparatorPredicate.Criterion, Integer> constantTransformer0 = new ConstantTransformer<ComparatorPredicate.Criterion, Integer>(integer0);
      // Undeclared exception!
      try { 
        CollectionUtils.size(constantTransformer0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported object type: org.apache.commons.collections4.functors.ConstantTransformer
         //
         verifyException("org.apache.commons.collections4.CollectionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Predicate<Object> predicate0 = UniquePredicate.uniquePredicate();
      Stack<Locale.FilteringMode> stack0 = new Stack<Locale.FilteringMode>();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.REJECT_EXTENDED_RANGES;
      stack0.add(locale_FilteringMode0);
      Predicate<Locale.FilteringMode> predicate1 = NullIsFalsePredicate.nullIsFalsePredicate((Predicate<? super Locale.FilteringMode>) predicate0);
      Collection<Locale.FilteringMode> collection0 = CollectionUtils.selectRejected((Iterable<? extends Locale.FilteringMode>) stack0, (Predicate<? super Locale.FilteringMode>) predicate1);
      assertFalse(collection0.contains(locale_FilteringMode0));
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Vector<Locale.FilteringMode> vector0 = new Vector<Locale.FilteringMode>();
      Predicate<Locale.FilteringMode> predicate0 = NullPredicate.nullPredicate();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.IGNORE_EXTENDED_RANGES;
      vector0.add(locale_FilteringMode0);
      Collection<Locale.FilteringMode> collection0 = CollectionUtils.selectRejected((Iterable<? extends Locale.FilteringMode>) vector0, (Predicate<? super Locale.FilteringMode>) predicate0);
      assertTrue(collection0.contains(locale_FilteringMode0));
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Locale.Category locale_Category0 = Locale.Category.DISPLAY;
      EqualPredicate<Locale.Category> equalPredicate0 = new EqualPredicate<Locale.Category>(locale_Category0);
      ArrayList<Locale.Category> arrayList0 = new ArrayList<Locale.Category>();
      Collection<Locale.Category> collection0 = CollectionUtils.selectRejected((Iterable<? extends Locale.Category>) arrayList0, (Predicate<? super Locale.Category>) equalPredicate0);
      Comparator<Locale.Category> comparator0 = (Comparator<Locale.Category>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      List<Locale.Category> list0 = CollectionUtils.collate((Iterable<? extends Locale.Category>) collection0, (Iterable<? extends Locale.Category>) arrayList0, (Comparator<? super Locale.Category>) comparator0);
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Predicate<Comparable<Integer>>[] predicateArray0 = (Predicate<Comparable<Integer>>[]) Array.newInstance(Predicate.class, 3);
      Collection<Comparable<Integer>> collection0 = CollectionUtils.selectRejected((Iterable<? extends Comparable<Integer>>) null, (Predicate<? super Comparable<Integer>>) predicateArray0[1]);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      LinkedHashSet<Object> linkedHashSet0 = new LinkedHashSet<Object>();
      LinkedHashSet<Object> linkedHashSet1 = CollectionUtils.select((Iterable<?>) linkedHashSet0, (Predicate<? super Object>) null, linkedHashSet0, linkedHashSet0);
      assertSame(linkedHashSet1, linkedHashSet0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      LinkedHashSet<Object> linkedHashSet0 = new LinkedHashSet<Object>();
      LinkedHashSet<Object> linkedHashSet1 = CollectionUtils.select((Iterable<?>) null, (Predicate<? super Object>) null, linkedHashSet0, linkedHashSet0);
      assertTrue(linkedHashSet1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Integer integer0 = new Integer(2626);
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      treeSet0.add(integer0);
      Predicate<Integer> predicate0 = NullPredicate.nullPredicate();
      Collection<Integer> collection0 = CollectionUtils.select((Iterable<? extends Integer>) treeSet0, (Predicate<? super Integer>) predicate0);
      assertFalse(collection0.contains(2626));
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      LinkedHashSet<Locale.IsoCountryCode> linkedHashSet0 = new LinkedHashSet<Locale.IsoCountryCode>(31);
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      PriorityQueue<Closure<Object>> priorityQueue0 = new PriorityQueue<Closure<Object>>(comparator0);
      Collection<Object> collection0 = CollectionUtils.unmodifiableCollection((Collection<?>) linkedHashSet0);
      Collection<Object> collection1 = CollectionUtils.select((Iterable<? extends Closure<Object>>) priorityQueue0, (Predicate<? super Closure<Object>>) null, collection0);
      assertFalse(collection1.contains(31));
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Integer integer0 = new Integer(1295);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Comparator<Integer> comparator0 = (Comparator<Integer>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      doReturn(0, 0, 0, 0, 0).when(comparator0).compare(anyInt() , anyInt());
      Predicate<Integer> predicate0 = ComparatorPredicate.comparatorPredicate(integer0, comparator0);
      Collection<Integer> collection0 = CollectionUtils.select((Iterable<? extends Integer>) list0, (Predicate<? super Integer>) predicate0);
      assertTrue(collection0.contains(1295));
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      OrPredicate<Integer> orPredicate0 = new OrPredicate<Integer>((Predicate<? super Integer>) null, (Predicate<? super Integer>) null);
      Collection<Integer> collection0 = CollectionUtils.select((Iterable<? extends Integer>) null, (Predicate<? super Integer>) orPredicate0);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Closure<Object>[] closureArray0 = (Closure<Object>[]) Array.newInstance(Closure.class, 2);
      CollectionUtils.reverseArray(closureArray0);
      assertEquals(2, closureArray0.length);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      List<Predicate<Integer>> list0 = List.of();
      // Undeclared exception!
      try { 
        CollectionUtils.removeCount((Collection<Predicate<Integer>>) list0, 0, (-2724));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // The count can't be less than 0.
         //
         verifyException("org.apache.commons.collections4.CollectionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Vector<Locale.Category> vector0 = new Vector<Locale.Category>();
      // Undeclared exception!
      try { 
        CollectionUtils.removeCount((Collection<Locale.Category>) vector0, 4609, 2);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // The sum of start index and count can't be greater than the size of collection.
         //
         verifyException("org.apache.commons.collections4.CollectionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Vector<Integer> vector0 = new Vector<Integer>(14);
      Integer integer0 = new Integer(14);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0);
      DefaultEquator<Integer> defaultEquator0 = DefaultEquator.defaultEquator();
      Collection<Integer> collection0 = CollectionUtils.removeAll((Iterable<Integer>) list0, (Iterable<? extends Integer>) vector0, (Equator<? super Integer>) defaultEquator0);
      assertTrue(collection0.contains(14));
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Integer integer0 = new Integer(1137);
      List<Integer> list0 = List.of(integer0);
      DefaultEquator<Integer> defaultEquator0 = DefaultEquator.defaultEquator();
      Collection<Integer> collection0 = CollectionUtils.removeAll((Iterable<Integer>) list0, (Iterable<? extends Integer>) list0, (Equator<? super Integer>) defaultEquator0);
      assertFalse(collection0.contains(1137));
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      Collection<List<Integer>> collection0 = CollectionUtils.permutations((Collection<Integer>) treeSet0);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      CircularFifoQueue<LinkedHashSet<Integer>> circularFifoQueue0 = new CircularFifoQueue<LinkedHashSet<Integer>>();
      int int0 = CollectionUtils.maxSize(circularFifoQueue0);
      assertEquals(32, int0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      Integer integer0 = new Integer(1295);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Predicate<Object>[] predicateArray0 = (Predicate<Object>[]) Array.newInstance(Predicate.class, 6);
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      Predicate<Object> predicate0 = ComparatorPredicate.comparatorPredicate((Object) null, comparator0);
      EqualPredicate<Object> equalPredicate0 = new EqualPredicate<Object>(predicate0);
      predicateArray0[3] = (Predicate<Object>) equalPredicate0;
      boolean boolean0 = CollectionUtils.matchesAll((Iterable<Integer>) list0, (Predicate<? super Integer>) predicateArray0[3]);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      ServiceLoader<Integer> serviceLoader0 = ServiceLoader.loadInstalled(class0);
      AllPredicate<Object> allPredicate0 = new AllPredicate<Object>((Predicate<? super Object>[]) null);
      OrPredicate<Integer> orPredicate0 = new OrPredicate<Integer>(allPredicate0, allPredicate0);
      boolean boolean0 = CollectionUtils.matchesAll((Iterable<Integer>) serviceLoader0, (Predicate<? super Integer>) orPredicate0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      ArrayDeque<ComparatorPredicate.Criterion> arrayDeque0 = new ArrayDeque<ComparatorPredicate.Criterion>();
      Iterator<ComparatorPredicate.Criterion> iterator0 = arrayDeque0.iterator();
      Integer integer0 = new Integer((-1682));
      ConstantTransformer<ComparatorPredicate.Criterion, Integer> constantTransformer0 = new ConstantTransformer<ComparatorPredicate.Criterion, Integer>(integer0);
      Collection<Integer> collection0 = CollectionUtils.collect(iterator0, (Transformer<? super ComparatorPredicate.Criterion, ? extends Integer>) constantTransformer0);
      boolean boolean0 = CollectionUtils.matchesAll((Iterable<Integer>) collection0, (Predicate<? super Integer>) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      HashSet<Collection<Integer>> hashSet0 = new HashSet<Collection<Integer>>();
      Integer integer0 = new Integer(2626);
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      treeSet0.add(integer0);
      boolean boolean0 = CollectionUtils.isSubCollection(treeSet0, hashSet0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      Integer integer0 = new Integer(2626);
      treeSet0.add(integer0);
      boolean boolean0 = CollectionUtils.isSubCollection(treeSet0, treeSet0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      HashSet<Collection<Integer>> hashSet0 = new HashSet<Collection<Integer>>();
      Integer integer0 = new Integer(5);
      List<Integer> list0 = List.of(integer0);
      boolean boolean0 = CollectionUtils.isProperSubCollection(hashSet0, list0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      boolean boolean0 = CollectionUtils.isProperSubCollection(treeSet0, treeSet0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      CircularFifoQueue<Object> circularFifoQueue0 = new CircularFifoQueue<Object>();
      boolean boolean0 = CollectionUtils.isNotEmpty(circularFifoQueue0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      CircularFifoQueue<Object> circularFifoQueue0 = new CircularFifoQueue<Object>();
      boolean boolean0 = CollectionUtils.isFull(circularFifoQueue0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      boolean boolean0 = CollectionUtils.isFull(linkedList0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      Integer integer0 = new Integer(2626);
      treeSet0.add(integer0);
      boolean boolean0 = CollectionUtils.isNotEmpty(treeSet0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      CircularFifoQueue<LinkOption> circularFifoQueue0 = new CircularFifoQueue<LinkOption>();
      boolean boolean0 = CollectionUtils.isEmpty(circularFifoQueue0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      Vector<Integer> vector0 = new Vector<Integer>(14);
      Integer integer0 = new Integer(14);
      vector0.add(integer0);
      Collection<Integer> collection0 = CollectionUtils.intersection((Iterable<? extends Integer>) vector0, (Iterable<? extends Integer>) vector0);
      assertTrue(collection0.contains(14));
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      DefaultEquator<Integer> defaultEquator0 = DefaultEquator.defaultEquator();
      CollectionUtils.hashCode((Collection<? extends Integer>) null, (Equator<? super Integer>) defaultEquator0);
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      DefaultEquator<Integer> defaultEquator0 = DefaultEquator.defaultEquator();
      Class<Integer> class0 = Integer.class;
      ServiceLoader<Integer> serviceLoader0 = ServiceLoader.load(class0);
      Predicate<Integer>[] predicateArray0 = (Predicate<Integer>[]) Array.newInstance(Predicate.class, 1);
      AnyPredicate<Integer> anyPredicate0 = new AnyPredicate<Integer>(predicateArray0);
      Collection<Integer> collection0 = CollectionUtils.select((Iterable<? extends Integer>) serviceLoader0, (Predicate<? super Integer>) anyPredicate0);
      CollectionUtils.hashCode((Collection<? extends Integer>) collection0, (Equator<? super Integer>) defaultEquator0);
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      Class<Integer> class0 = Integer.TYPE;
      ServiceLoader<Integer> serviceLoader0 = ServiceLoader.loadInstalled(class0);
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      Integer integer0 = new Integer(10);
      treeSet0.add(integer0);
      Comparator<Integer> comparator0 = (Comparator<Integer>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      List<Integer> list0 = CollectionUtils.collate((Iterable<? extends Integer>) treeSet0, (Iterable<? extends Integer>) serviceLoader0, (Comparator<? super Integer>) comparator0, false);
      Map<Integer, Integer> map0 = CollectionUtils.getCardinalityMap((Iterable<? extends Integer>) list0);
      Transformer<Integer, Integer> transformer0 = MapTransformer.mapTransformer((Map<? super Integer, ? extends Integer>) map0);
      EqualPredicate<Integer> equalPredicate0 = new EqualPredicate<Integer>(integer0);
      TransformedPredicate<Integer> transformedPredicate0 = new TransformedPredicate<Integer>(transformer0, equalPredicate0);
      // Undeclared exception!
      try { 
        CollectionUtils.predicatedCollection((Collection<Integer>) treeSet0, (Predicate<? super Integer>) transformedPredicate0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add Object '10' - Predicate 'org.apache.commons.collections4.functors.TransformedPredicate@4' rejected it
         //
         verifyException("org.apache.commons.collections4.collection.PredicatedCollection", e);
      }
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      TreeSet<Locale.IsoCountryCode> treeSet0 = new TreeSet<Locale.IsoCountryCode>();
      Map<Locale.IsoCountryCode, Integer> map0 = CollectionUtils.getCardinalityMap((Iterable<? extends Locale.IsoCountryCode>) treeSet0);
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      // Undeclared exception!
      try { 
        CollectionUtils.get((Object) null, 774);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported object type: null
         //
         verifyException("org.apache.commons.collections4.CollectionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      // Undeclared exception!
      try { 
        CollectionUtils.get((Object) treeSet0, (-271));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index cannot be negative: -271
         //
         verifyException("org.apache.commons.collections4.CollectionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      Class<Locale.FilteringMode> class0 = Locale.FilteringMode.class;
      ServiceLoader<Locale.FilteringMode> serviceLoader0 = ServiceLoader.load(class0, (ClassLoader) null);
      Iterator<Locale.FilteringMode> iterator0 = serviceLoader0.iterator();
      TransformerClosure<Locale.FilteringMode> transformerClosure0 = CollectionUtils.forAllDo(iterator0, (TransformerClosure<Locale.FilteringMode>) null);
      assertNull(transformerClosure0);
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      Closure<Object>[] closureArray0 = (Closure<Object>[]) Array.newInstance(Closure.class, 0);
      ChainedClosure<Object> chainedClosure0 = new ChainedClosure<Object>(closureArray0);
      PriorityQueue<LinkedList<Integer>> priorityQueue0 = new PriorityQueue<LinkedList<Integer>>(1000);
      ChainedClosure<Object> chainedClosure1 = CollectionUtils.forAllDo((Iterable<LinkedList<Integer>>) priorityQueue0, chainedClosure0);
      assertSame(chainedClosure0, chainedClosure1);
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      StringTokenizer stringTokenizer0 = new StringTokenizer(">**igWfBV]G:TU");
      Iterator<Object> iterator0 = stringTokenizer0.asIterator();
      NOPClosure<Object> nOPClosure0 = (NOPClosure<Object>) mock(NOPClosure.class, new ViolatedAssumptionAnswer());
      Object object0 = CollectionUtils.forAllButLastDo(iterator0, nOPClosure0);
      assertEquals(">**igWfBV]G:TU", object0);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Iterator<Object> iterator0 = linkedList0.descendingIterator();
      Object object0 = CollectionUtils.forAllButLastDo(iterator0, (Closure<Object>) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      LinkedHashSet<Integer> linkedHashSet0 = new LinkedHashSet<Integer>();
      List<Integer> list0 = CollectionUtils.collate((Iterable<? extends Integer>) linkedHashSet0, (Iterable<? extends Integer>) linkedHashSet0, true);
      FixedSizeList<Integer> fixedSizeList0 = FixedSizeList.fixedSizeList(list0);
      ExceptionClosure<Integer> exceptionClosure0 = (ExceptionClosure<Integer>) mock(ExceptionClosure.class, new ViolatedAssumptionAnswer());
      Integer integer0 = CollectionUtils.forAllButLastDo((Iterable<Integer>) fixedSizeList0, exceptionClosure0);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      ServiceLoader<Integer> serviceLoader0 = ServiceLoader.loadInstalled(class0);
      AllPredicate<Object> allPredicate0 = new AllPredicate<Object>((Predicate<? super Object>[]) null);
      Integer integer0 = CollectionUtils.find((Iterable<Integer>) serviceLoader0, (Predicate<? super Integer>) allPredicate0);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      Integer integer0 = new Integer(5);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0);
      Predicate<Object>[] predicateArray0 = (Predicate<Object>[]) Array.newInstance(Predicate.class, 1);
      Vector<Integer> vector0 = new Vector<Integer>(list0);
      Integer integer1 = CollectionUtils.find((Iterable<Integer>) vector0, (Predicate<? super Integer>) predicateArray0[0]);
      assertNull(integer1);
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      LinkedHashSet<Object> linkedHashSet0 = new LinkedHashSet<Object>();
      linkedHashSet0.add((Object) null);
      Predicate<Object> predicate0 = UniquePredicate.uniquePredicate();
      CollectionUtils.select((Iterable<?>) linkedHashSet0, (Predicate<? super Object>) predicate0, linkedHashSet0, linkedHashSet0);
      boolean boolean0 = CollectionUtils.filter((Iterable<Object>) linkedHashSet0, (Predicate<? super Object>) predicate0);
      assertTrue(linkedHashSet0.isEmpty());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      Integer integer0 = new Integer(1295);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0, integer0);
      Comparator<Integer> comparator0 = (Comparator<Integer>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      doReturn(0, 0, 0, 0, 0).when(comparator0).compare(anyInt() , anyInt());
      Predicate<Integer> predicate0 = ComparatorPredicate.comparatorPredicate(integer0, comparator0);
      boolean boolean0 = CollectionUtils.filter((Iterable<Integer>) list0, (Predicate<? super Integer>) predicate0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      Iterator<ComparatorPredicate.Criterion> iterator0 = (Iterator<ComparatorPredicate.Criterion>) mock(Iterator.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(iterator0).hasNext();
      Factory<Integer> factory0 = ExceptionFactory.exceptionFactory();
      FactoryTransformer<ComparatorPredicate.Criterion, Integer> factoryTransformer0 = new FactoryTransformer<ComparatorPredicate.Criterion, Integer>(factory0);
      Collection<Integer> collection0 = CollectionUtils.collect(iterator0, (Transformer<? super ComparatorPredicate.Criterion, ? extends Integer>) factoryTransformer0);
      boolean boolean0 = CollectionUtils.filter((Iterable<Integer>) collection0, (Predicate<? super Integer>) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      PriorityQueue<LinkOption> priorityQueue0 = new PriorityQueue<LinkOption>();
      LinkOption linkOption0 = LinkOption.NOFOLLOW_LINKS;
      priorityQueue0.add(linkOption0);
      LinkOption linkOption1 = CollectionUtils.extractSingleton((Collection<LinkOption>) priorityQueue0);
      assertEquals(LinkOption.NOFOLLOW_LINKS, linkOption1);
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      Collection<Object> collection0 = CollectionUtils.emptyIfNull((Collection<Object>) null);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      LinkedList<LinkedList<Locale.IsoCountryCode>> linkedList0 = new LinkedList<LinkedList<Locale.IsoCountryCode>>();
      Collection<LinkedList<Locale.IsoCountryCode>> collection0 = CollectionUtils.emptyIfNull((Collection<LinkedList<Locale.IsoCountryCode>>) linkedList0);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      Integer integer0 = new Integer(5);
      List<Integer> list0 = List.of(integer0, integer0, integer0, integer0, integer0, integer0);
      Integer[] integerArray0 = new Integer[4];
      integerArray0[0] = integer0;
      boolean boolean0 = CollectionUtils.containsAny((Collection<?>) list0, integerArray0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      Integer integer0 = new Integer(2626);
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      treeSet0.add(integer0);
      Integer[] integerArray0 = new Integer[6];
      integerArray0[0] = integer0;
      boolean boolean0 = CollectionUtils.containsAny((Collection<?>) treeSet0, integerArray0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      Integer integer0 = new Integer(2626);
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      treeSet0.add(integer0);
      Integer[] integerArray0 = new Integer[6];
      boolean boolean0 = CollectionUtils.containsAny((Collection<?>) treeSet0, integerArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      ArrayList<InstanceofPredicate> arrayList0 = new ArrayList<InstanceofPredicate>();
      Integer[] integerArray0 = new Integer[0];
      boolean boolean0 = CollectionUtils.containsAny((Collection<?>) arrayList0, integerArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test147()  throws Throwable  {
      PriorityQueue<LinkOption> priorityQueue0 = new PriorityQueue<LinkOption>();
      Vector<Integer> vector0 = new Vector<Integer>(14);
      Integer integer0 = new Integer(14);
      vector0.add(integer0);
      List<LinkOption> list0 = CollectionUtils.collate((Iterable<? extends LinkOption>) priorityQueue0, (Iterable<? extends LinkOption>) priorityQueue0);
      boolean boolean0 = CollectionUtils.containsAny((Collection<?>) list0, (Collection<?>) vector0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test148()  throws Throwable  {
      Collection<LinkedHashSet<Integer>> collection0 = CollectionUtils.emptyCollection();
      LinkedHashSet<Object> linkedHashSet0 = new LinkedHashSet<Object>();
      linkedHashSet0.add(collection0);
      linkedHashSet0.add((Object) null);
      boolean boolean0 = CollectionUtils.containsAll(linkedHashSet0, linkedHashSet0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test149()  throws Throwable  {
      LinkedHashSet<Object> linkedHashSet0 = new LinkedHashSet<Object>();
      LinkedHashSet<Object> linkedHashSet1 = new LinkedHashSet<Object>();
      linkedHashSet0.add(linkedHashSet1);
      boolean boolean0 = CollectionUtils.containsAll(linkedHashSet1, linkedHashSet0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test150()  throws Throwable  {
      HashSet<Object> hashSet0 = new HashSet<Object>(1291);
      Comparator<Object> comparator0 = (Comparator<Object>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      List<Object> list0 = CollectionUtils.collate((Iterable<?>) hashSet0, (Iterable<?>) hashSet0, (Comparator<? super Object>) comparator0);
      FixedSizeList<Object> fixedSizeList0 = FixedSizeList.fixedSizeList(list0);
      PriorityQueue<Predicate<Object>> priorityQueue0 = new PriorityQueue<Predicate<Object>>();
      boolean boolean0 = CollectionUtils.containsAll(fixedSizeList0, priorityQueue0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test151()  throws Throwable  {
      HashSet<Integer> hashSet0 = new HashSet<Integer>();
      Integer integer0 = new Integer(1042);
      hashSet0.add(integer0);
      DefaultEquator<Integer> defaultEquator0 = DefaultEquator.defaultEquator();
      boolean boolean0 = CollectionUtils.isEqualCollection((Collection<? extends Integer>) hashSet0, (Collection<? extends Integer>) hashSet0, (Equator<? super Integer>) defaultEquator0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test152()  throws Throwable  {
      Transformer<LinkOption, LinkOption> transformer0 = CloneTransformer.cloneTransformer();
      Collection<LinkOption> collection0 = CollectionUtils.collect((Iterable<LinkOption>) null, (Transformer<? super LinkOption, ? extends LinkOption>) transformer0);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test153()  throws Throwable  {
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.REJECT_EXTENDED_RANGES;
      ConstantTransformer<Object, Locale.FilteringMode> constantTransformer0 = new ConstantTransformer<Object, Locale.FilteringMode>(locale_FilteringMode0);
      EnumSet<Locale.FilteringMode> enumSet0 = EnumSet.of(locale_FilteringMode0, locale_FilteringMode0, locale_FilteringMode0, locale_FilteringMode0);
      Collection<Locale.FilteringMode> collection0 = CollectionUtils.collect((Iterable<? extends Comparable<Locale.FilteringMode>>) null, (Transformer<? super Comparable<Locale.FilteringMode>, ? extends Locale.FilteringMode>) constantTransformer0, (Collection<Locale.FilteringMode>) enumSet0);
      assertTrue(collection0.contains(locale_FilteringMode0));
  }

  @Test(timeout = 4000)
  public void test154()  throws Throwable  {
      Integer integer0 = new Integer(2626);
      Integer integer1 = new Integer(1651);
      List<Integer> list0 = List.of(integer1, integer1, integer1, integer1, integer0, integer1, integer1);
      List<Integer> list1 = CollectionUtils.collate((Iterable<? extends Integer>) list0, (Iterable<? extends Integer>) list0, false);
      assertEquals(5, list1.size());
  }

  @Test(timeout = 4000)
  public void test155()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      ServiceLoader<Integer> serviceLoader0 = ServiceLoader.loadInstalled(class0);
      Collection<Integer> collection0 = CollectionUtils.intersection((Iterable<? extends Integer>) serviceLoader0, (Iterable<? extends Integer>) serviceLoader0);
      assertNotNull(collection0);
  }

  @Test(timeout = 4000)
  public void test156()  throws Throwable  {
      PriorityQueue<LinkOption> priorityQueue0 = new PriorityQueue<LinkOption>();
      LinkOption[] linkOptionArray0 = new LinkOption[0];
      boolean boolean0 = CollectionUtils.addAll((Collection<LinkOption>) priorityQueue0, linkOptionArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test157()  throws Throwable  {
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      Integer integer0 = new Integer(2626);
      treeSet0.add(integer0);
      Collection<Object> collection0 = CollectionUtils.disjunction((Iterable<?>) treeSet0, (Iterable<?>) treeSet0);
      assertFalse(collection0.contains(2626));
  }

  @Test(timeout = 4000)
  public void test158()  throws Throwable  {
      TreeSet<Integer> treeSet0 = new TreeSet<Integer>();
      Integer integer0 = new Integer(2626);
      treeSet0.add(integer0);
      Collection<Integer> collection0 = CollectionUtils.union((Iterable<? extends Integer>) treeSet0, (Iterable<? extends Integer>) treeSet0);
      assertTrue(collection0.contains(2626));
  }

  @Test(timeout = 4000)
  public void test159()  throws Throwable  {
      Integer integer0 = new Integer(5);
      List<Integer> list0 = List.of(integer0);
      DefaultEquator<Integer> defaultEquator0 = DefaultEquator.defaultEquator();
      ArrayDeque<Integer> arrayDeque0 = new ArrayDeque<Integer>(list0);
      Collection<Integer> collection0 = CollectionUtils.retainAll((Iterable<Integer>) list0, (Iterable<? extends Integer>) arrayDeque0, (Equator<? super Integer>) defaultEquator0);
      assertTrue(collection0.contains(5));
  }

  @Test(timeout = 4000)
  public void test160()  throws Throwable  {
      Class<Locale.Category> class0 = Locale.Category.class;
      ClassLoader classLoader0 = ClassLoader.getPlatformClassLoader();
      ServiceLoader<Locale.Category> serviceLoader0 = ServiceLoader.load(class0, classLoader0);
      Locale.Category locale_Category0 = Locale.Category.DISPLAY;
      EqualPredicate<Locale.Category> equalPredicate0 = new EqualPredicate<Locale.Category>(locale_Category0);
      Collection<Locale.Category> collection0 = CollectionUtils.selectRejected((Iterable<? extends Locale.Category>) serviceLoader0, (Predicate<? super Locale.Category>) equalPredicate0);
      Comparator<Locale.Category> comparator0 = (Comparator<Locale.Category>) mock(Comparator.class, new ViolatedAssumptionAnswer());
      List<Locale.Category> list0 = CollectionUtils.collate((Iterable<? extends Locale.Category>) collection0, (Iterable<? extends Locale.Category>) collection0, (Comparator<? super Locale.Category>) comparator0);
      // Undeclared exception!
      try { 
        CollectionUtils.removeCount((Collection<Locale.Category>) list0, (-2312), (-2312));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // The start index can't be less than 0.
         //
         verifyException("org.apache.commons.collections4.CollectionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test161()  throws Throwable  {
      HashSet<Collection<Integer>> hashSet0 = new HashSet<Collection<Integer>>();
      Collection<Collection<Integer>> collection0 = CollectionUtils.retainAll((Collection<Collection<Integer>>) hashSet0, (Collection<?>) hashSet0);
      Integer integer0 = new Integer(1137);
      List<Integer> list0 = List.of(integer0);
      hashSet0.add(list0);
      boolean boolean0 = CollectionUtils.isProperSubCollection(hashSet0, collection0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test162()  throws Throwable  {
      Class<Integer> class0 = Integer.TYPE;
      ServiceLoader<Integer> serviceLoader0 = ServiceLoader.loadInstalled(class0);
      List<Integer> list0 = CollectionUtils.collate((Iterable<? extends Integer>) serviceLoader0, (Iterable<? extends Integer>) serviceLoader0);
      // Undeclared exception!
      try { 
        CollectionUtils.removeCount((Collection<Integer>) list0, 1830, 0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // The sum of start index and count can't be greater than the size of collection.
         //
         verifyException("org.apache.commons.collections4.CollectionUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test163()  throws Throwable  {
      Vector<Integer> vector0 = new Vector<Integer>(14);
      List<Collection<Integer>> list0 = List.of((Collection<Integer>) vector0, (Collection<Integer>) vector0, (Collection<Integer>) vector0);
      int int0 = CollectionUtils.cardinality((Collection<Integer>) vector0, (Iterable<? super Collection<Integer>>) list0);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test164()  throws Throwable  {
      HashMap<Locale.FilteringMode, Collection<Locale.FilteringMode>> hashMap0 = new HashMap<Locale.FilteringMode, Collection<Locale.FilteringMode>>();
      // Undeclared exception!
      try { 
        CollectionUtils.get((Map<Locale.FilteringMode, Collection<Locale.FilteringMode>>) hashMap0, 512);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Entry does not exist: 512
         //
         verifyException("org.apache.commons.collections4.IteratorUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test165()  throws Throwable  {
      Integer integer0 = new Integer(1);
      List<Integer> list0 = List.of(integer0);
      FixedSizeList<Integer> fixedSizeList0 = FixedSizeList.fixedSizeList(list0);
      ListIterator<Integer> listIterator0 = fixedSizeList0.listIterator();
      // Undeclared exception!
      try { 
        CollectionUtils.get((Iterator<Integer>) listIterator0, 2241);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Entry does not exist: 2240
         //
         verifyException("org.apache.commons.collections4.IteratorUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test166()  throws Throwable  {
      Class<Integer> class0 = Integer.class;
      ServiceLoader<Integer> serviceLoader0 = ServiceLoader.loadInstalled(class0);
      List<Integer> list0 = CollectionUtils.collate((Iterable<? extends Integer>) serviceLoader0, (Iterable<? extends Integer>) serviceLoader0, true);
      Collection<Integer> collection0 = CollectionUtils.synchronizedCollection((Collection<Integer>) list0);
      assertNotNull(collection0);
  }
}
